//! Generated by Nectar compiler — do not edit.
//! Source: .nectar → Rust → cargo build → WASM

// Fast WASM allocator — replaces dlmalloc for better allocation performance
#[global_allocator]
static ALLOCATOR: lol_alloc::AssumeSingleThreaded<lol_alloc::FreeListAllocator> =
    unsafe { lol_alloc::AssumeSingleThreaded::new(lol_alloc::FreeListAllocator::new()) };

#[allow(unused_imports)]
use honeycomb::element::ElementTree;
use honeycomb::layout;
use honeycomb::canvas_app::CanvasTextMeasurer;
use honeycomb::canvas_syscalls::*;
use std::cell::RefCell;
use serde::Deserialize;

/// Scratch buffer for fetch responses, storage reads, hash reads
const SCRATCH_SIZE: usize = 4 * 1024 * 1024; // 4MB — handles 10K+ product API responses
static mut SCRATCH: [u8; SCRATCH_SIZE] = [0u8; SCRATCH_SIZE];

/// Helper: read a string from WASM memory via syscall that writes into a buffer
fn read_storage(key: &str) -> String {
    unsafe {
        let len = storage_get(key.as_ptr(), key.len() as u32, SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        if len == 0 { return String::new(); }
        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()
    }
}

fn write_storage(key: &str, val: &str) {
    unsafe { storage_set(key.as_ptr(), key.len() as u32, val.as_ptr(), val.len() as u32); }
}

fn remove_storage(key: &str) {
    unsafe { storage_remove(key.as_ptr(), key.len() as u32); }
}

fn get_hash() -> String {
    unsafe {
        let len = get_location_hash(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        if len == 0 { return String::new(); }
        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()
    }
}

fn set_hash(hash: &str) {
    unsafe { set_location_hash(hash.as_ptr(), hash.len() as u32); }
}

fn fetch_get(url: &str, cb_idx: u32) {
    unsafe { fetch_request(url.as_ptr(), url.len() as u32, 0, std::ptr::null(), 0, cb_idx); }
}

fn fetch_post(url: &str, body: &[u8], cb_idx: u32) {
    unsafe {
        fetch_set_header("Content-Type".as_ptr(), 12, "application/json".as_ptr(), 16);
        fetch_request(url.as_ptr(), url.len() as u32, 1, body.as_ptr(), body.len() as u32, cb_idx);
    }
}

fn read_response() -> (i32, Vec<u8>) {
    unsafe {
        let status = fetch_response_status();
        let len = fetch_response_body(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        (status, SCRATCH[..len as usize].to_vec())
    }
}

fn set_auth_header(token: &str) {
    let val = format!("Bearer {}", token);
    unsafe { fetch_set_header("Authorization".as_ptr(), 13, val.as_ptr(), val.len() as u32); }
}

fn with_tree<R>(f: impl FnOnce(&mut ElementTree) -> R) -> R {
    honeycomb::wasm_api::TREE.with(|t| f(&mut t.borrow_mut()))
}

fn perf_now() -> f64 { unsafe { performance_now() } }
static mut INIT_START: f64 = 0.0;

fn update_metric_text(name: &str, value: &str) {
    honeycomb::canvas_app::METRIC_TEXT_IDS.with(|m| {
        let ids: Vec<(String, u32)> = m.borrow().clone();
        // Try wasm_api::TREE first (handler may have just rebuilt here)
        honeycomb::wasm_api::TREE.with(|t| {
            let mut tree = t.borrow_mut();
            for (n, id) in &ids {
                if n == name {
                    if let Some(el) = tree.get_mut(*id) { el.text = Some(value.to_string()); }
                }
            }
        });
        // Also try AppState.tree (for filter/sort that don't rebuild)
        honeycomb::canvas_app::STATE.with(|s| {
            if let Some(ref mut app) = *s.borrow_mut() {
                for (n, id) in &ids {
                    if n == name {
                        if let Some(el) = app.tree.get_mut(*id) { el.text = Some(value.to_string()); }
                    }
                }
            }
        });
    });
}

fn filter_by(attr: &str, value: &str) {
    honeycomb::canvas_app::wasm_filter_by_attr(
        attr.as_ptr(), attr.len() as u32, value.as_ptr(), value.len() as u32);
}
fn to_ms_string(start: f64, end: f64) -> String {
    let elapsed = ((end - start) * 100.0) as i32;
    let d = elapsed / 100;
    let c = elapsed - d * 100;
    if c < 10 { format!("{}ms", d) } else { format!("{}.{}ms", d, c) }
}

struct PillsDemoState {
    _element_ids: Vec<u32>,
    _card_cats: Vec<(u32, String)>,
    total_ms: String,
    heap_ms: String,
    last_op_ms: String,
}

thread_local! {
    static PILLSDEMO_STATE: RefCell<PillsDemoState> = RefCell::new(PillsDemoState {
        _element_ids: Vec::new(),
        _card_cats: Vec::new(),
        total_ms: String::new(),
        heap_ms: String::new(),
        last_op_ms: String::new(),
    });
}

fn pillsdemo_mount() {
    PILLSDEMO_STATE.with(|_state_cell| {
        let _state_ref = _state_cell.borrow();
        with_tree(|tree| {
            let root = tree.root_id();
            let el_0 = tree.create("div");
            tree.append_child(root, el_0);
            tree.set_style(el_0, "direction", "vertical");
            tree.set_style(el_0, "padding", "40px");
            tree.set_style(el_0, "gap", "20px");
            tree.set_style(el_0, "background-color", "#FFFFFF");
            tree.set_style(el_0, "width", "fill");
            tree.set_style(el_0, "height", "fill");
            let el_1 = tree.create("span");
            tree.append_child(el_0, el_1);
            tree.set_style(el_1, "font-size", "20px");
            tree.set_style(el_1, "font-weight", "700");
            tree.set_style(el_1, "color", "#111827");
            if let Some(el) = tree.get_mut(el_1) { el.text = Some("Status Pills".into()); }
            let el_2 = tree.create("div");
            tree.append_child(el_0, el_2);
            tree.set_style(el_2, "direction", "vertical");
            tree.set_style(el_2, "gap", "16px");
            let el_3 = tree.create("div");
            tree.append_child(el_2, el_3);
            tree.set_style(el_3, "direction", "horizontal");
            tree.set_style(el_3, "gap", "12px");
            tree.set_style(el_3, "align", "center");
            let el_4 = tree.create("span");
            tree.append_child(el_3, el_4);
            tree.set_style(el_4, "width", "hug");
            tree.set_style(el_4, "height", "hug");
            tree.set_style(el_4, "padding-left", "12px");
            tree.set_style(el_4, "padding-right", "12px");
            tree.set_style(el_4, "padding-top", "4px");
            tree.set_style(el_4, "padding-bottom", "4px");
            tree.set_style(el_4, "background-color", "#FEE2E2");
            tree.set_style(el_4, "border-radius", "9999px");
            tree.set_style(el_4, "font-size", "13px");
            tree.set_style(el_4, "font-weight", "500");
            tree.set_style(el_4, "color", "#DC2626");
            if let Some(el) = tree.get_mut(el_4) { el.text = Some("Cancelled".into()); }
            let el_5 = tree.create("div");
            tree.append_child(el_2, el_5);
            tree.set_style(el_5, "direction", "horizontal");
            tree.set_style(el_5, "gap", "12px");
            tree.set_style(el_5, "align", "center");
            let el_6 = tree.create("span");
            tree.append_child(el_5, el_6);
            tree.set_style(el_6, "width", "hug");
            tree.set_style(el_6, "height", "hug");
            tree.set_style(el_6, "padding-left", "12px");
            tree.set_style(el_6, "padding-right", "12px");
            tree.set_style(el_6, "padding-top", "4px");
            tree.set_style(el_6, "padding-bottom", "4px");
            tree.set_style(el_6, "background-color", "#F3F4F6");
            tree.set_style(el_6, "border-radius", "9999px");
            tree.set_style(el_6, "font-size", "13px");
            tree.set_style(el_6, "font-weight", "500");
            tree.set_style(el_6, "color", "#374151");
            if let Some(el) = tree.get_mut(el_6) { el.text = Some("Draft".into()); }
            let el_7 = tree.create("div");
            tree.append_child(el_2, el_7);
            tree.set_style(el_7, "direction", "horizontal");
            tree.set_style(el_7, "gap", "12px");
            tree.set_style(el_7, "align", "center");
            let el_8 = tree.create("span");
            tree.append_child(el_7, el_8);
            tree.set_style(el_8, "width", "hug");
            tree.set_style(el_8, "height", "hug");
            tree.set_style(el_8, "padding-left", "12px");
            tree.set_style(el_8, "padding-right", "12px");
            tree.set_style(el_8, "padding-top", "4px");
            tree.set_style(el_8, "padding-bottom", "4px");
            tree.set_style(el_8, "background-color", "#EEF2FF");
            tree.set_style(el_8, "border-radius", "9999px");
            tree.set_style(el_8, "font-size", "13px");
            tree.set_style(el_8, "font-weight", "500");
            tree.set_style(el_8, "color", "#4F46E5");
            if let Some(el) = tree.get_mut(el_8) { el.text = Some("Active".into()); }
            let el_9 = tree.create("div");
            tree.append_child(el_2, el_9);
            tree.set_style(el_9, "direction", "horizontal");
            tree.set_style(el_9, "gap", "12px");
            tree.set_style(el_9, "align", "center");
            let el_10 = tree.create("span");
            tree.append_child(el_9, el_10);
            tree.set_style(el_10, "width", "hug");
            tree.set_style(el_10, "height", "hug");
            tree.set_style(el_10, "padding-left", "12px");
            tree.set_style(el_10, "padding-right", "12px");
            tree.set_style(el_10, "padding-top", "4px");
            tree.set_style(el_10, "padding-bottom", "4px");
            tree.set_style(el_10, "background-color", "#F3F4F6");
            tree.set_style(el_10, "border-radius", "9999px");
            tree.set_style(el_10, "font-size", "13px");
            tree.set_style(el_10, "font-weight", "500");
            tree.set_style(el_10, "color", "#374151");
            if let Some(el) = tree.get_mut(el_10) { el.text = Some("Draft".into()); }
            let el_11 = tree.create("div");
            tree.append_child(el_2, el_11);
            tree.set_style(el_11, "direction", "horizontal");
            tree.set_style(el_11, "gap", "12px");
            tree.set_style(el_11, "align", "center");
            let el_12 = tree.create("span");
            tree.append_child(el_11, el_12);
            tree.set_style(el_12, "width", "hug");
            tree.set_style(el_12, "height", "hug");
            tree.set_style(el_12, "padding-left", "12px");
            tree.set_style(el_12, "padding-right", "12px");
            tree.set_style(el_12, "padding-top", "4px");
            tree.set_style(el_12, "padding-bottom", "4px");
            tree.set_style(el_12, "background-color", "#DCFCE7");
            tree.set_style(el_12, "border-radius", "9999px");
            tree.set_style(el_12, "font-size", "13px");
            tree.set_style(el_12, "font-weight", "500");
            tree.set_style(el_12, "color", "#16A34A");
            if let Some(el) = tree.get_mut(el_12) { el.text = Some("Prep Complete".into()); }
            let el_13 = tree.create("div");
            tree.append_child(el_2, el_13);
            tree.set_style(el_13, "direction", "horizontal");
            tree.set_style(el_13, "gap", "12px");
            tree.set_style(el_13, "align", "center");
            let el_14 = tree.create("span");
            tree.append_child(el_13, el_14);
            tree.set_style(el_14, "width", "hug");
            tree.set_style(el_14, "height", "hug");
            tree.set_style(el_14, "padding-left", "12px");
            tree.set_style(el_14, "padding-right", "12px");
            tree.set_style(el_14, "padding-top", "4px");
            tree.set_style(el_14, "padding-bottom", "4px");
            tree.set_style(el_14, "background-color", "#FEF3C7");
            tree.set_style(el_14, "border-radius", "9999px");
            tree.set_style(el_14, "font-size", "13px");
            tree.set_style(el_14, "font-weight", "500");
            tree.set_style(el_14, "color", "#D97706");
            if let Some(el) = tree.get_mut(el_14) { el.text = Some("Pending".into()); }
            let el_15 = tree.create("div");
            tree.append_child(el_2, el_15);
            tree.set_style(el_15, "direction", "horizontal");
            tree.set_style(el_15, "gap", "12px");
            tree.set_style(el_15, "align", "center");
            let el_16 = tree.create("span");
            tree.append_child(el_15, el_16);
            tree.set_style(el_16, "width", "hug");
            tree.set_style(el_16, "height", "hug");
            tree.set_style(el_16, "padding-left", "12px");
            tree.set_style(el_16, "padding-right", "12px");
            tree.set_style(el_16, "padding-top", "4px");
            tree.set_style(el_16, "padding-bottom", "4px");
            tree.set_style(el_16, "background-color", "#DBEAFE");
            tree.set_style(el_16, "border-radius", "9999px");
            tree.set_style(el_16, "font-size", "13px");
            tree.set_style(el_16, "font-weight", "500");
            tree.set_style(el_16, "color", "#2563EB");
            if let Some(el) = tree.get_mut(el_16) { el.text = Some("In Progress".into()); }
            let el_17 = tree.create("span");
            tree.append_child(el_0, el_17);
            tree.set_style(el_17, "font-size", "20px");
            tree.set_style(el_17, "font-weight", "700");
            tree.set_style(el_17, "color", "#111827");
            tree.set_style(el_17, "padding-top", "20px");
            if let Some(el) = tree.get_mut(el_17) { el.text = Some("Inline Pills".into()); }
            let el_18 = tree.create("div");
            tree.append_child(el_0, el_18);
            tree.set_style(el_18, "direction", "horizontal");
            tree.set_style(el_18, "gap", "8px");
            tree.set_style(el_18, "align", "center");
            tree.set_style(el_18, "wrap", "true");
            let el_19 = tree.create("span");
            tree.append_child(el_18, el_19);
            tree.set_style(el_19, "width", "hug");
            tree.set_style(el_19, "height", "hug");
            tree.set_style(el_19, "padding-left", "10px");
            tree.set_style(el_19, "padding-right", "10px");
            tree.set_style(el_19, "padding-top", "3px");
            tree.set_style(el_19, "padding-bottom", "3px");
            tree.set_style(el_19, "background-color", "#FEE2E2");
            tree.set_style(el_19, "border-radius", "9999px");
            tree.set_style(el_19, "font-size", "12px");
            tree.set_style(el_19, "font-weight", "500");
            tree.set_style(el_19, "color", "#DC2626");
            if let Some(el) = tree.get_mut(el_19) { el.text = Some("Cancelled".into()); }
            let el_20 = tree.create("span");
            tree.append_child(el_18, el_20);
            tree.set_style(el_20, "width", "hug");
            tree.set_style(el_20, "height", "hug");
            tree.set_style(el_20, "padding-left", "10px");
            tree.set_style(el_20, "padding-right", "10px");
            tree.set_style(el_20, "padding-top", "3px");
            tree.set_style(el_20, "padding-bottom", "3px");
            tree.set_style(el_20, "background-color", "#DCFCE7");
            tree.set_style(el_20, "border-radius", "9999px");
            tree.set_style(el_20, "font-size", "12px");
            tree.set_style(el_20, "font-weight", "500");
            tree.set_style(el_20, "color", "#16A34A");
            if let Some(el) = tree.get_mut(el_20) { el.text = Some("Active".into()); }
            let el_21 = tree.create("span");
            tree.append_child(el_18, el_21);
            tree.set_style(el_21, "width", "hug");
            tree.set_style(el_21, "height", "hug");
            tree.set_style(el_21, "padding-left", "10px");
            tree.set_style(el_21, "padding-right", "10px");
            tree.set_style(el_21, "padding-top", "3px");
            tree.set_style(el_21, "padding-bottom", "3px");
            tree.set_style(el_21, "background-color", "#EEF2FF");
            tree.set_style(el_21, "border-radius", "9999px");
            tree.set_style(el_21, "font-size", "12px");
            tree.set_style(el_21, "font-weight", "500");
            tree.set_style(el_21, "color", "#4F46E5");
            if let Some(el) = tree.get_mut(el_21) { el.text = Some("Scheduled".into()); }
            let el_22 = tree.create("span");
            tree.append_child(el_18, el_22);
            tree.set_style(el_22, "width", "hug");
            tree.set_style(el_22, "height", "hug");
            tree.set_style(el_22, "padding-left", "10px");
            tree.set_style(el_22, "padding-right", "10px");
            tree.set_style(el_22, "padding-top", "3px");
            tree.set_style(el_22, "padding-bottom", "3px");
            tree.set_style(el_22, "background-color", "#FEF3C7");
            tree.set_style(el_22, "border-radius", "9999px");
            tree.set_style(el_22, "font-size", "12px");
            tree.set_style(el_22, "font-weight", "500");
            tree.set_style(el_22, "color", "#D97706");
            if let Some(el) = tree.get_mut(el_22) { el.text = Some("Pending".into()); }
            let el_23 = tree.create("span");
            tree.append_child(el_18, el_23);
            tree.set_style(el_23, "width", "hug");
            tree.set_style(el_23, "height", "hug");
            tree.set_style(el_23, "padding-left", "10px");
            tree.set_style(el_23, "padding-right", "10px");
            tree.set_style(el_23, "padding-top", "3px");
            tree.set_style(el_23, "padding-bottom", "3px");
            tree.set_style(el_23, "background-color", "#F3F4F6");
            tree.set_style(el_23, "border-radius", "9999px");
            tree.set_style(el_23, "font-size", "12px");
            tree.set_style(el_23, "font-weight", "500");
            tree.set_style(el_23, "color", "#374151");
            if let Some(el) = tree.get_mut(el_23) { el.text = Some("Draft".into()); }
        });
    });
}

// ── Render: layout only (painting done by Honeycomb's app_render) ──

fn render() {
    honeycomb::wasm_api::TREE.with(|t| {
        let mut tree = t.borrow_mut();
        let mut measurer = CanvasTextMeasurer { canvas_id: 0 };
        let vw = unsafe { canvas_get_width() };
        let vh = unsafe { canvas_get_height() };
        layout::compute(&mut tree, vw, 999999.0, &mut measurer);
    });
}

#[no_mangle]
pub extern "C" fn nectar_init(_vw: f32, _vh: f32) {
    let _init_t0 = perf_now();
    unsafe { INIT_START = _init_t0; }
    pillsdemo_mount();
    let _init_elapsed = to_ms_string(_init_t0, perf_now());
    PILLSDEMO_STATE.with(|s| s.borrow_mut().total_ms = _init_elapsed.clone());
    update_metric_text("total_ms", &_init_elapsed);
    let _heap = PILLSDEMO_STATE.with(|s| s.borrow().heap_ms.clone());
    update_metric_text("heap_ms", &_heap);
}

