//! Rust codegen backend — generates Rust source that compiles with Honeycomb.
//!
//! .nectar → AST → Rust source → cargo build → single WASM binary
//!
//! The generated code uses Honeycomb's element tree API directly:
//!   tree.create("div"), tree.set_style(id, "width", "100px"), tree.append_child(parent, child)
//!
//! This produces ONE binary containing both the app logic and the rendering engine.

use crate::ast::*;

pub struct RustCodegen {
    output: String,
    indent: usize,
    in_handler: bool, // true when inside a handler (state is `state.field`), false in render (needs STATE.with)
    current_comp: String, // current component name for state access
}

impl RustCodegen {
    pub fn new() -> Self {
        Self {
            output: String::with_capacity(8192),
            indent: 0,
            in_handler: false,
            current_comp: String::new(),
        }
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.emit_prelude();

        for item in &program.items {
            match item {
                Item::Component(comp) => self.emit_component(comp),
                Item::Struct(s) => self.emit_struct(s),
                _ => {} // Other items not yet supported in canvas backend
            }
        }

        self.emit_main(program);

        std::mem::take(&mut self.output)
    }

    fn emit_prelude(&mut self) {
        self.line("//! Generated by Nectar compiler — do not edit.");
        self.line("//! Source: .nectar → Rust → cargo build → WASM");
        self.line("");
        self.line("use honeycomb::element::ElementTree;");
        self.line("use honeycomb::layout;");
        self.line("use honeycomb::measure::EstimateMeasurer;");
        self.line("use honeycomb::canvas_syscalls::*;");
        self.line("use std::cell::RefCell;");
        self.line("");
        self.line("thread_local! {");
        self.line("    static TREE: RefCell<ElementTree> = RefCell::new(ElementTree::new());");
        self.line("    static MEASURER: RefCell<EstimateMeasurer> = RefCell::new(EstimateMeasurer);");
        self.line("}");
        self.line("");
        self.line("fn with_tree<R>(f: impl FnOnce(&mut ElementTree) -> R) -> R {");
        self.line("    TREE.with(|t| f(&mut t.borrow_mut()))");
        self.line("}");
        self.line("");
    }

    fn emit_struct(&mut self, s: &StructDef) {
        self.line("#[derive(Clone, Default)]");
        self.line(&format!("struct {} {{", s.name));
        self.indent += 1;
        for field in &s.fields {
            let rust_type = self.type_to_rust(&field.ty);
            self.line(&format!("{}: {},", field.name, rust_type));
        }
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_component(&mut self, comp: &Component) {
        let name = &comp.name;
        self.current_comp = name.clone();

        // Component state struct
        self.line(&format!("struct {}State {{", name));
        self.indent += 1;
        for field in &comp.state {
            let rust_type = if let Some(ref ty) = field.ty {
                self.type_to_rust(ty)
            } else {
                "i32".to_string() // fallback when type is inferred
            };
            self.line(&format!("{}: {},", field.name, rust_type));
        }
        // Element IDs for reactive updates
        self.line("// Element IDs (stored for signal updates)");
        self.line("_element_ids: Vec<u32>,");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // State storage
        self.line("thread_local! {");
        self.line(&format!("    static {}_STATE: RefCell<{}State> = RefCell::new({}State {{",
            name.to_uppercase(), name, name));
        self.indent += 2;
        for field in &comp.state {
            let default = self.expr_to_rust(&field.initializer, "");
            self.line(&format!("{}: {},", field.name, default));
        }
        self.line("_element_ids: Vec::new(),");
        self.indent -= 2;
        self.line("    });");
        self.line("}");
        self.line("");

        // Mount function — builds the element tree
        self.line(&format!("fn {}_mount() {{", name.to_lowercase()));
        self.indent += 1;
        // Read state into local variables BEFORE entering the tree closure.
        for field in &comp.state {
            let ty = if let Some(ref t) = field.ty {
                self.type_to_rust(t)
            } else {
                "i32".to_string()
            };
            if ty.starts_with("Vec") || ty == "String" {
                self.line(&format!("let {} = {}_STATE.with(|s| s.borrow().{}.clone());",
                    field.name, name.to_uppercase(), field.name));
            } else {
                self.line(&format!("let {} = {}_STATE.with(|s| s.borrow().{});",
                    field.name, name.to_uppercase(), field.name));
            }
        }
        self.line("");
        self.line("with_tree(|tree| {");
        self.indent += 1;
        self.line("let root = tree.root_id();");

        // Emit render block body — uses local variables, not self.field
        self.in_handler = false; // use local vars, not state.field
        self.emit_template_node(&comp.render.body, "root", name);

        self.indent -= 1;
        self.line("});");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // Handler functions
        for (i, method) in comp.methods.iter().enumerate() {
            self.emit_handler(name, method, i);
        }
    }

    fn emit_template_node(&mut self, node: &TemplateNode, parent_var: &str, comp_name: &str) {
        match node {
            TemplateNode::Element(el) => {
                let var = format!("el_{}", self.fresh_id());
                self.line(&format!("let {} = tree.create(\"{}\");", var, el.tag));
                self.line(&format!("tree.append_child({}, {});", parent_var, var));

                // Attributes
                for attr in &el.attributes {
                    match attr {
                        Attribute::Static { name, value } => {
                            if name == "style" {
                                // Parse inline style string into individual set_style calls
                                for part in value.split(';') {
                                    let part = part.trim();
                                    if let Some((prop, val)) = part.split_once(':') {
                                        let prop = prop.trim();
                                        let val = val.trim();
                                        self.line(&format!("tree.set_style({}, \"{}\", \"{}\");", var, prop, val));
                                    }
                                }
                            } else if name == "placeholder" {
                                self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.placeholder = Some(\"{}\".into()); }}", var, value));
                            }
                        }
                        Attribute::Dynamic { name, value } => {
                            let val_rust = self.expr_to_rust(value, comp_name);
                            self.line(&format!("// dynamic attr: {} = {}", name, val_rust));
                        }
                        Attribute::EventHandler { event, handler } => {
                            if event == "click" {
                                if let Some(method_name) = self.extract_handler_name(handler) {
                                    self.line(&format!("// on:click -> {}", method_name));
                                    self.line(&format!("tree.add_event({}, \"click\", 0); // callback wired in event loop", var));
                                }
                            }
                        }
                        Attribute::Bind { property, signal } => {
                            self.line(&format!("// bind:{} = {}", property, signal));
                        }
                        Attribute::Aria { name, value } => {
                            let val_rust = self.expr_to_rust(value, comp_name);
                            self.line(&format!("// aria-{} = {}", name, val_rust));
                        }
                        Attribute::Role { value } => {
                            self.line(&format!("// role = {}", value));
                        }
                    }
                }

                // Children
                for child in &el.children {
                    self.emit_template_node(child, &var, comp_name);
                }
            }
            TemplateNode::TextLiteral(text) => {
                let var = format!("txt_{}", self.fresh_id());
                self.line(&format!("let {} = tree.create(\"#text\");", var));
                self.line(&format!("tree.append_child({}, {});", parent_var, var));
                // Escape quotes in text
                let escaped = text.replace('\\', "\\\\").replace('"', "\\\"");
                self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.text = Some(\"{}\".into()); }}", var, escaped));
            }
            TemplateNode::Expression(expr) => {
                // Dynamic text — read from component state
                let var = format!("dyn_{}", self.fresh_id());
                self.line(&format!("let {} = tree.create(\"#text\");", var));
                self.line(&format!("tree.append_child({}, {});", parent_var, var));
                let rust_expr = self.expr_to_rust(expr, comp_name);
                self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.text = Some({}.into()); }}", var, rust_expr));
            }
            TemplateNode::Fragment(children) => {
                for child in children {
                    self.emit_template_node(child, parent_var, comp_name);
                }
            }
            TemplateNode::TemplateFor { binding, iterator, children, .. } => {
                let iter_rust = self.expr_to_rust(iterator, comp_name);
                self.line(&format!("for {} in {} {{", binding, iter_rust));
                self.indent += 1;
                for child in children {
                    self.emit_template_node(child, parent_var, comp_name);
                }
                self.indent -= 1;
                self.line("}");
            }
            TemplateNode::TemplateIf { condition, then_children, else_children } => {
                let cond_rust = self.expr_to_rust(condition, comp_name);
                self.line(&format!("if {} {{", cond_rust));
                self.indent += 1;
                for child in then_children {
                    self.emit_template_node(child, parent_var, comp_name);
                }
                self.indent -= 1;
                if let Some(else_nodes) = else_children {
                    self.line("} else {");
                    self.indent += 1;
                    for child in else_nodes {
                        self.emit_template_node(child, parent_var, comp_name);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            _ => {} // Link, Outlet, Layout, TemplateMatch not yet supported
        }
    }

    fn emit_handler(&mut self, comp_name: &str, method: &Function, _idx: usize) {
        let is_init = method.name.starts_with("init");

        self.line(&format!("fn {}_{}() {{", comp_name.to_lowercase(), method.name));
        self.indent += 1;
        self.line(&format!("{}_STATE.with(|s| {{", comp_name.to_uppercase()));
        self.indent += 1;
        self.line("let mut state = s.borrow_mut();");
        self.in_handler = true;

        // Emit method body
        for stmt in &method.body.stmts {
            self.emit_stmt(stmt, comp_name);
        }

        self.in_handler = false;
        self.indent -= 1;
        self.line("});");

        // Init methods don't re-render — they're called before first mount
        if !is_init {
            self.line("// Re-render after state change");
            self.line("with_tree(|tree| {");
            self.indent += 1;
            self.line("let root = tree.root_id();");
            self.line("if let Some(el) = tree.get_mut(root) { el.children.clear(); }");
            self.indent -= 1;
            self.line("});");
            self.line(&format!("{}_mount();", comp_name.to_lowercase()));
            self.line("render();");
        }

        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_stmt(&mut self, stmt: &Stmt, comp_name: &str) {
        match stmt {
            Stmt::Expr(Expr::Assign { target, value }) => {
                let target_rust = self.expr_to_rust(target, comp_name);
                let value_rust = self.expr_to_rust(value, comp_name);
                self.line(&format!("{} = {};", target_rust, value_rust));
            }
            Stmt::Expr(Expr::While { condition, body }) => {
                let cond = self.expr_to_rust(condition, comp_name);
                self.line(&format!("while {} {{", cond));
                self.indent += 1;
                for s in &body.stmts {
                    self.emit_stmt(s, comp_name);
                }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Expr(Expr::For { binding, iterator, body }) => {
                let iter = self.expr_to_rust(iterator, comp_name);
                self.line(&format!("for {} in {} {{", binding, iter));
                self.indent += 1;
                for s in &body.stmts {
                    self.emit_stmt(s, comp_name);
                }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Expr(Expr::If { condition, then_block, else_block }) => {
                let cond = self.expr_to_rust(condition, comp_name);
                self.line(&format!("if {} {{", cond));
                self.indent += 1;
                for s in &then_block.stmts {
                    self.emit_stmt(s, comp_name);
                }
                self.indent -= 1;
                if let Some(else_blk) = else_block {
                    self.line("} else {");
                    self.indent += 1;
                    for s in &else_blk.stmts {
                        self.emit_stmt(s, comp_name);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::Expr(expr) => {
                let e = self.expr_to_rust(expr, comp_name);
                self.line(&format!("{};", e));
            }
            Stmt::Return(Some(expr)) => {
                let e = self.expr_to_rust(expr, comp_name);
                self.line(&format!("return {};", e));
            }
            Stmt::Return(None) => {
                self.line("return;");
            }
            Stmt::Let { name, value, mutable, .. } => {
                let val = self.expr_to_rust(value, comp_name);
                if *mutable {
                    self.line(&format!("let mut {} = {};", name, val));
                } else {
                    self.line(&format!("let {} = {};", name, val));
                }
            }
            _ => {
                self.line("// TODO: unsupported statement");
            }
        }
    }

    fn expr_to_rust(&self, expr: &Expr, comp_name: &str) -> String {
        match expr {
            Expr::Integer(n) => format!("{}", n),
            Expr::Float(f) => format!("{:.1}", f),
            Expr::StringLit(s) => format!("\"{}\"", s),
            Expr::Bool(b) => format!("{}", b),
            Expr::Ident(name) => {
                if name.starts_with("self.") {
                    format!("{}_STATE.with(|s| s.borrow().{})", comp_name.to_uppercase(), &name[5..])
                } else {
                    name.clone()
                }
            }
            Expr::SelfExpr => {
                if self.in_handler { "state".to_string() } else { "self".to_string() }
            }
            Expr::FieldAccess { object, field } => {
                // self.field →
                //   handler: state.field (inside STATE.with closure)
                //   render:  field (local variable extracted before with_tree)
                if matches!(**object, Expr::SelfExpr) {
                    if self.in_handler {
                        format!("state.{}", field)
                    } else {
                        field.clone() // local variable
                    }
                } else {
                    let obj = self.expr_to_rust(object, comp_name);
                    format!("{}.{}", obj, field)
                }
            }
            Expr::Binary { left, op, right } => {
                let l = self.expr_to_rust(left, comp_name);
                let r = self.expr_to_rust(right, comp_name);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::Neq => "!=",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::Lte => "<=",
                    BinOp::Gte => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FnCall { callee, args } => {
                let callee_str = self.expr_to_rust(callee, comp_name);
                if callee_str == "format" && !args.is_empty() {
                    // format("...", arg1, arg2) → format!("...", arg1, arg2)
                    let fmt = self.expr_to_rust(&args[0], comp_name);
                    let rest: Vec<String> = args[1..].iter().map(|a| self.expr_to_rust(a, comp_name)).collect();
                    if rest.is_empty() {
                        format!("format!({})", fmt)
                    } else {
                        format!("format!({}, {})", fmt, rest.join(", "))
                    }
                } else {
                    let a: Vec<String> = args.iter().map(|a| self.expr_to_rust(a, comp_name)).collect();
                    format!("{}({})", callee_str, a.join(", "))
                }
            }
            Expr::MethodCall { object, method, args } => {
                let obj = self.expr_to_rust(object, comp_name);
                let a: Vec<String> = args.iter().map(|a| self.expr_to_rust(a, comp_name)).collect();
                // .cmp() takes a reference — auto-add & to the argument
                if method == "cmp" && a.len() == 1 && !a[0].starts_with('&') {
                    format!("{}.cmp(&{})", obj, a[0])
                } else {
                    format!("{}.{}({})", obj, method, a.join(", "))
                }
            }
            Expr::Range { start, end } => {
                let s = self.expr_to_rust(start, comp_name);
                let e = self.expr_to_rust(end, comp_name);
                format!("{}..{}", s, e)
            }
            Expr::ArrayLit(items) => {
                let elems: Vec<String> = items.iter().map(|e| self.expr_to_rust(e, comp_name)).collect();
                format!("vec![{}]", elems.join(", "))
            }
            Expr::Unary { op, operand } => {
                let o = self.expr_to_rust(operand, comp_name);
                match op {
                    UnaryOp::Neg => format!("(-{})", o),
                    UnaryOp::Not => format!("(!{})", o),
                }
            }
            Expr::Index { object, index } => {
                let obj = self.expr_to_rust(object, comp_name);
                let idx = self.expr_to_rust(index, comp_name);
                format!("{}[{}]", obj, idx)
            }
            Expr::Assign { target, value } => {
                let t = self.expr_to_rust(target, comp_name);
                let v = self.expr_to_rust(value, comp_name);
                format!("{} = {}", t, v)
            }
            Expr::Closure { params, body } => {
                let p: Vec<String> = params.iter().map(|(name, ty)| {
                    if let Some(t) = ty {
                        format!("{}: {}", name, self.type_to_rust(t))
                    } else {
                        name.clone()
                    }
                }).collect();
                let b = self.expr_to_rust(body, comp_name);
                format!("|{}| {{ {} }}", p.join(", "), b)
            }
            Expr::Block(block) => {
                let stmts: Vec<String> = block.stmts.iter().map(|s| {
                    match s {
                        Stmt::Expr(e) => self.expr_to_rust(e, comp_name),
                        Stmt::Let { name, value, mutable, .. } => {
                            let val = self.expr_to_rust(value, comp_name);
                            if *mutable {
                                format!("let mut {} = {}", name, val)
                            } else {
                                format!("let {} = {}", name, val)
                            }
                        }
                        Stmt::Return(Some(e)) => format!("return {}", self.expr_to_rust(e, comp_name)),
                        Stmt::Return(None) => "return".to_string(),
                        _ => "()".to_string(),
                    }
                }).collect();
                if stmts.len() == 1 {
                    stmts[0].clone()
                } else {
                    format!("{{ {} }}", stmts.join("; "))
                }
            }
            Expr::If { condition, then_block, else_block } => {
                let cond = self.expr_to_rust(condition, comp_name);
                let then_stmts: Vec<String> = then_block.stmts.iter().map(|s| {
                    match s { Stmt::Expr(e) => self.expr_to_rust(e, comp_name), _ => "()".into() }
                }).collect();
                let then_str = then_stmts.last().cloned().unwrap_or("()".into());
                if let Some(else_blk) = else_block {
                    let else_stmts: Vec<String> = else_blk.stmts.iter().map(|s| {
                        match s { Stmt::Expr(e) => self.expr_to_rust(e, comp_name), _ => "()".into() }
                    }).collect();
                    let else_str = else_stmts.last().cloned().unwrap_or("()".into());
                    format!("if {} {{ {} }} else {{ {} }}", cond, then_str, else_str)
                } else {
                    format!("if {} {{ {} }}", cond, then_str)
                }
            }
            _ => "/* unsupported expr */".to_string(),
        }
    }

    fn emit_main(&mut self, program: &Program) {
        // Find the first component
        let comp_name = program.items.iter().find_map(|item| {
            if let Item::Component(c) = item { Some(c.name.clone()) } else { None }
        }).unwrap_or_else(|| "App".to_string());

        self.line("// ── Render loop ──────────────────────────────────────");
        self.line("");
        self.line("fn render() {");
        self.indent += 1;
        self.line("TREE.with(|t| {");
        self.indent += 1;
        self.line("let mut tree = t.borrow_mut();");
        self.line("let mut measurer = EstimateMeasurer;");
        self.line("let vw = unsafe { canvas_get_width() };");
        self.line("let vh = unsafe { canvas_get_height() };");
        self.line("layout::compute(&mut tree, vw, vh, &mut measurer);");
        self.indent -= 1;
        self.line("});");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // WASM export — builds the element tree in Honeycomb's wasm_api TREE.
        // Called BEFORE app_init so Honeycomb detects the pre-built tree.
        // Check if the component has init methods (init_*, or just init)
        let comp = program.items.iter().find_map(|item| {
            if let Item::Component(c) = item { Some(c) } else { None }
        });
        let init_methods: Vec<String> = comp.map(|c| {
            c.methods.iter()
                .filter(|m| m.name.starts_with("init"))
                .map(|m| format!("{}_{}", comp_name.to_lowercase(), m.name))
                .collect()
        }).unwrap_or_default();

        self.line("#[no_mangle]");
        self.line(&format!("pub extern \"C\" fn nectar_init(_vw: f32, _vh: f32) {{"));
        self.indent += 1;
        // Call init methods first (populate arrays, etc.)
        for init_fn in &init_methods {
            self.line(&format!("{}();", init_fn));
        }
        self.line(&format!("{}_mount();", comp_name.to_lowercase()));
        self.indent -= 1;
        self.line("}");
    }

    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Named(name) => {
                match name.as_str() {
                    "i32" => "i32".into(),
                    "i64" => "i64".into(),
                    "f32" => "f32".into(),
                    "f64" => "f64".into(),
                    "bool" => "bool".into(),
                    "String" | "string" => "String".into(),
                    other => other.to_string(),
                }
            }
            Type::Array(inner) => format!("Vec<{}>", self.type_to_rust(inner)),
            Type::Option(inner) => format!("Option<{}>", self.type_to_rust(inner)),
            Type::Result { ok, err } => format!("Result<{}, {}>", self.type_to_rust(ok), self.type_to_rust(err)),
            Type::Tuple(types) => {
                let parts: Vec<String> = types.iter().map(|t| self.type_to_rust(t)).collect();
                format!("({})", parts.join(", "))
            }
            Type::Generic { name, args } => {
                let parts: Vec<String> = args.iter().map(|t| self.type_to_rust(t)).collect();
                format!("{}<{}>", name, parts.join(", "))
            }
            Type::Reference { mutable, inner, .. } => {
                if *mutable {
                    format!("&mut {}", self.type_to_rust(inner))
                } else {
                    format!("&{}", self.type_to_rust(inner))
                }
            }
            Type::Function { params, ret } => {
                let p: Vec<String> = params.iter().map(|t| self.type_to_rust(t)).collect();
                format!("fn({}) -> {}", p.join(", "), self.type_to_rust(ret))
            }
        }
    }

    fn extract_handler_name(&self, expr: &Expr) -> Option<String> {
        match expr {
            Expr::FieldAccess { field, .. } => Some(field.clone()),
            Expr::MethodCall { method, .. } => Some(method.clone()),
            Expr::Ident(name) => Some(name.clone()),
            _ => None,
        }
    }

    fn fresh_id(&self) -> u32 {
        use std::sync::atomic::{AtomicU32, Ordering};
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        COUNTER.fetch_add(1, Ordering::Relaxed)
    }
}
