//! Rust codegen backend — generates Rust source that compiles with Honeycomb.
//!
//! .nectar → AST → Rust source → cargo build → single WASM binary
//!
//! The generated code uses Honeycomb's element tree API directly:
//!   tree.create("div"), tree.set_style(id, "width", "100px"), tree.append_child(parent, child)
//!
//! This produces ONE binary containing both the app logic and the rendering engine.

use crate::ast::*;

/// A detected filter pattern: {for x in self.items { {if self.state_field == "All" || x.item_field == self.state_field { ... }} }}
#[derive(Debug, Clone)]
struct FilterPattern {
    state_field: String,   // e.g. "active_cat" — the state field that controls filtering
    item_field: String,    // e.g. "category" — the product field used as filter key
}

pub struct RustCodegen {
    output: String,
    indent: usize,
    in_handler: bool,
    current_comp: String,
    handler_indices: std::collections::HashMap<String, usize>,
    filter_patterns: Vec<FilterPattern>, // detected from template analysis
    last_element_var: String, // last element variable created by emit_template_node
}

impl RustCodegen {
    pub fn new() -> Self {
        Self {
            output: String::with_capacity(8192),
            indent: 0,
            in_handler: false,
            current_comp: String::new(),
            handler_indices: std::collections::HashMap::new(),
            filter_patterns: Vec::new(),
            last_element_var: String::new(),
        }
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.emit_prelude();

        for item in &program.items {
            match item {
                Item::Component(comp) => self.emit_component(comp),
                Item::Struct(s) => self.emit_struct(s),
                _ => {} // Other items not yet supported in canvas backend
            }
        }

        self.emit_main(program);

        std::mem::take(&mut self.output)
    }

    fn emit_prelude(&mut self) {
        self.line("//! Generated by Nectar compiler — do not edit.");
        self.line("//! Source: .nectar → Rust → cargo build → WASM");
        self.line("");
        self.line("#[allow(unused_imports)]");
        self.line("use honeycomb::element::ElementTree;");
        self.line("use honeycomb::layout;");
        self.line("use honeycomb::measure::EstimateMeasurer;");
        self.line("use honeycomb::canvas_syscalls::*;");
        self.line("use std::cell::RefCell;");
        self.line("use serde::Deserialize;");
        self.line("");
        self.line("/// Scratch buffer for fetch responses, storage reads, hash reads");
        self.line("const SCRATCH_SIZE: usize = 4 * 1024 * 1024; // 4MB — handles 10K+ product API responses");
        self.line("static mut SCRATCH: [u8; SCRATCH_SIZE] = [0u8; SCRATCH_SIZE];");
        self.line("");
        self.line("/// Helper: read a string from WASM memory via syscall that writes into a buffer");
        self.line("fn read_storage(key: &str) -> String {");
        self.line("    unsafe {");
        self.line("        let len = storage_get(key.as_ptr(), key.len() as u32, SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);");
        self.line("        if len == 0 { return String::new(); }");
        self.line("        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("fn write_storage(key: &str, val: &str) {");
        self.line("    unsafe { storage_set(key.as_ptr(), key.len() as u32, val.as_ptr(), val.len() as u32); }");
        self.line("}");
        self.line("");
        self.line("fn remove_storage(key: &str) {");
        self.line("    unsafe { storage_remove(key.as_ptr(), key.len() as u32); }");
        self.line("}");
        self.line("");
        self.line("fn get_hash() -> String {");
        self.line("    unsafe {");
        self.line("        let len = get_location_hash(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);");
        self.line("        if len == 0 { return String::new(); }");
        self.line("        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("fn set_hash(hash: &str) {");
        self.line("    unsafe { set_location_hash(hash.as_ptr(), hash.len() as u32); }");
        self.line("}");
        self.line("");
        self.line("fn fetch_get(url: &str, cb_idx: u32) {");
        self.line("    unsafe { fetch_request(url.as_ptr(), url.len() as u32, 0, std::ptr::null(), 0, cb_idx); }");
        self.line("}");
        self.line("");
        self.line("fn fetch_post(url: &str, body: &[u8], cb_idx: u32) {");
        self.line("    unsafe {");
        self.line("        fetch_set_header(\"Content-Type\".as_ptr(), 12, \"application/json\".as_ptr(), 16);");
        self.line("        fetch_request(url.as_ptr(), url.len() as u32, 1, body.as_ptr(), body.len() as u32, cb_idx);");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("fn read_response() -> (i32, Vec<u8>) {");
        self.line("    unsafe {");
        self.line("        let status = fetch_response_status();");
        self.line("        let len = fetch_response_body(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);");
        self.line("        (status, SCRATCH[..len as usize].to_vec())");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("fn set_auth_header(token: &str) {");
        self.line("    let val = format!(\"Bearer {}\", token);");
        self.line("    unsafe { fetch_set_header(\"Authorization\".as_ptr(), 13, val.as_ptr(), val.len() as u32); }");
        self.line("}");
        self.line("");
        self.line("fn with_tree<R>(f: impl FnOnce(&mut ElementTree) -> R) -> R {");
        self.line("    honeycomb::wasm_api::TREE.with(|t| f(&mut t.borrow_mut()))");
        self.line("}");
        self.line("");
        self.line("fn perf_now() -> f64 { unsafe { performance_now() } }");
        self.line("static mut INIT_START: f64 = 0.0;");
        self.line("");
        // Update registered metric text nodes — tries wasm_api::TREE first (handler may have rebuilt there),
        // then AppState.tree, to handle both in-handler and post-sync contexts.
        self.line("fn update_metric_text(name: &str, value: &str) {");
        self.line("    honeycomb::canvas_app::METRIC_TEXT_IDS.with(|m| {");
        self.line("        let ids: Vec<(String, u32)> = m.borrow().clone();");
        self.line("        // Try wasm_api::TREE first (handler may have just rebuilt here)");
        self.line("        honeycomb::wasm_api::TREE.with(|t| {");
        self.line("            let mut tree = t.borrow_mut();");
        self.line("            for (n, id) in &ids {");
        self.line("                if n == name {");
        self.line("                    if let Some(el) = tree.get_mut(*id) { el.text = Some(value.to_string()); }");
        self.line("                }");
        self.line("            }");
        self.line("        });");
        self.line("        // Also try AppState.tree (for filter/sort that don't rebuild)");
        self.line("        honeycomb::canvas_app::STATE.with(|s| {");
        self.line("            if let Some(ref mut app) = *s.borrow_mut() {");
        self.line("                for (n, id) in &ids {");
        self.line("                    if n == name {");
        self.line("                        if let Some(el) = app.tree.get_mut(*id) { el.text = Some(value.to_string()); }");
        self.line("                    }");
        self.line("                }");
        self.line("            }");
        self.line("        });");
        self.line("    });");
        self.line("}");
        self.line("");
        self.line("fn filter_by(attr: &str, value: &str) {");
        self.line("    honeycomb::canvas_app::wasm_filter_by_attr(");
        self.line("        attr.as_ptr(), attr.len() as u32, value.as_ptr(), value.len() as u32);");
        self.line("}");
        self.line("fn to_ms_string(start: f64, end: f64) -> String {");
        self.line("    let elapsed = ((end - start) * 100.0) as i32;");
        self.line("    let d = elapsed / 100;");
        self.line("    let c = elapsed - d * 100;");
        self.line("    if c < 10 { format!(\"{}ms\", d) } else { format!(\"{}.{}ms\", d, c) }");
        self.line("}");
        self.line("");
    }

    /// Scan template tree for filter patterns: {for x in self.items { {if self.field == "All" || x.attr == self.field { ... }} }}
    fn detect_filter_patterns(&mut self, node: &TemplateNode, for_binding: Option<&str>) {
        match node {
            TemplateNode::TemplateFor { binding, children, .. } => {
                for child in children {
                    self.detect_filter_patterns(child, Some(binding));
                }
            }
            TemplateNode::TemplateIf { condition, then_children, .. } if for_binding.is_some() => {
                // Inside a {for}, look for condition that references self.X
                if let Some(pattern) = self.extract_filter_from_condition(condition, for_binding.unwrap()) {
                    self.filter_patterns.push(pattern);
                }
                for child in then_children {
                    self.detect_filter_patterns(child, for_binding);
                }
            }
            TemplateNode::Element(el) => {
                for child in &el.children {
                    self.detect_filter_patterns(child, for_binding);
                }
            }
            TemplateNode::Fragment(children) => {
                for child in children {
                    self.detect_filter_patterns(child, for_binding);
                }
            }
            _ => {}
        }
    }

    /// Extract filter pattern from a condition expression.
    /// Looks for: self.X == "All" || binding.Y == self.X
    fn extract_filter_from_condition(&self, expr: &Expr, binding: &str) -> Option<FilterPattern> {
        // Handle: self.field == "All" || product.field == self.field
        if let Expr::Binary { op: BinOp::Or, left, right } = expr {
            let state_field = self.find_self_field_in_eq(left)?;
            let item_field = self.find_binding_field_in_eq(right, binding)?;
            return Some(FilterPattern { state_field, item_field });
        }
        // Handle: product.field == self.field (without the "All" check)
        if let Expr::Binary { op: BinOp::Eq, .. } = expr {
            if let (Some(item_field), Some(state_field)) = (
                self.find_binding_field_in_eq(expr, binding),
                self.find_self_field_in_eq(expr),
            ) {
                return Some(FilterPattern { state_field, item_field });
            }
        }
        None
    }

    /// Find self.X in an equality expression
    fn find_self_field_in_eq(&self, expr: &Expr) -> Option<String> {
        if let Expr::Binary { op: BinOp::Eq, left, right } = expr {
            if let Expr::FieldAccess { object, field } = &**left {
                if matches!(**object, Expr::SelfExpr) { return Some(field.clone()); }
            }
            if let Expr::FieldAccess { object, field } = &**right {
                if matches!(**object, Expr::SelfExpr) { return Some(field.clone()); }
            }
        }
        None
    }

    /// Find binding.Y in an equality expression
    fn find_binding_field_in_eq(&self, expr: &Expr, binding: &str) -> Option<String> {
        if let Expr::Binary { op: BinOp::Eq, left, right } = expr {
            if let Expr::FieldAccess { object, field } = &**left {
                if let Expr::Ident(name) = &**object {
                    if name == binding { return Some(field.clone()); }
                }
            }
            if let Expr::FieldAccess { object, field } = &**right {
                if let Expr::Ident(name) = &**object {
                    if name == binding { return Some(field.clone()); }
                }
            }
        }
        None
    }

    /// Check if a handler only assigns to a specific state field
    fn handler_only_sets_field(&self, method: &Function, field_name: &str) -> bool {
        if method.body.stmts.len() != 1 { return false; }
        if let Stmt::Expr(Expr::Assign { target, .. }) = &method.body.stmts[0] {
            if let Expr::FieldAccess { object, field } = &**target {
                return matches!(**object, Expr::SelfExpr) && field == field_name;
            }
        }
        false
    }

    fn emit_struct(&mut self, s: &StructDef) {
        self.line("#[derive(Clone, Default, Deserialize)]");
        self.line(&format!("struct {} {{", s.name));
        self.indent += 1;
        for field in &s.fields {
            let rust_type = self.type_to_rust(&field.ty);
            self.line(&format!("{}: {},", field.name, rust_type));
        }
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_component(&mut self, comp: &Component) {
        let name = &comp.name;
        self.current_comp = name.clone();

        // Component state struct
        self.line(&format!("struct {}State {{", name));
        self.indent += 1;
        for field in &comp.state {
            let rust_type = if let Some(ref ty) = field.ty {
                self.type_to_rust(ty)
            } else {
                "i32".to_string() // fallback when type is inferred
            };
            self.line(&format!("{}: {},", field.name, rust_type));
        }
        // Element IDs for reactive updates
        self.line("_element_ids: Vec<u32>,");
        // Card tracking for O(1) filter toggle (card_id, category_string)
        self.line("_card_cats: Vec<(u32, String)>,");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // State storage
        self.line("thread_local! {");
        self.line(&format!("    static {}_STATE: RefCell<{}State> = RefCell::new({}State {{",
            name.to_uppercase(), name, name));
        self.indent += 2;
        for field in &comp.state {
            let default = self.expr_to_rust(&field.initializer, "");
            // String fields need .to_string() when initialized from a string literal
            let ty_str = field.ty.as_ref().map(|t| self.type_to_rust(t)).unwrap_or_default();
            if ty_str == "String" && default.starts_with('"') {
                self.line(&format!("{}: {}.to_string(),", field.name, default));
            } else {
                self.line(&format!("{}: {},", field.name, default));
            }
        }
        self.line("_element_ids: Vec::new(),");
        self.line("_card_cats: Vec::new(),");
        self.indent -= 2;
        self.line("    });");
        self.line("}");
        self.line("");

        // Mount function — builds the element tree
        self.line(&format!("fn {}_mount() {{", name.to_lowercase()));
        self.indent += 1;
        // Borrow state for the duration of mount — avoid cloning Vec<Product> (40K String allocs)
        self.line(&format!("{}_STATE.with(|_state_cell| {{", name.to_uppercase()));
        self.indent += 1;
        self.line("let _state_ref = _state_cell.borrow();");
        // Create local refs/copies for each field
        for field in &comp.state {
            let ty = if let Some(ref t) = field.ty {
                self.type_to_rust(t)
            } else {
                "i32".to_string()
            };
            if ty.starts_with("Vec") {
                // Borrow by reference — zero allocation
                self.line(&format!("let {} = &_state_ref.{};", field.name, field.name));
            } else if ty == "String" {
                // Clone strings (small, needed as owned for text nodes)
                self.line(&format!("let {} = _state_ref.{}.clone();", field.name, field.name));
            } else {
                // Copy scalars
                self.line(&format!("let {} = _state_ref.{};", field.name, field.name));
            }
        }
        self.line("with_tree(|tree| {");
        self.indent += 1;
        self.line("let root = tree.root_id();");

        // Detect filter patterns in template: {for x in items { {if self.field == ... { }} }}
        self.filter_patterns.clear();
        self.detect_filter_patterns(&comp.render.body, None);

        // Build handler index map: non-init methods → callback indices
        self.handler_indices.clear();
        let mut cb_idx = 0;
        for method in &comp.methods {
            if !method.name.starts_with("init") {
                self.handler_indices.insert(method.name.clone(), cb_idx);
                cb_idx += 1;
            }
        }

        // Emit render block body — uses local variables, not self.field
        self.in_handler = false; // use local vars, not state.field
        self.emit_template_node(&comp.render.body, "root", name);

        self.indent -= 1;
        self.line("});"); // close with_tree
        self.indent -= 1;
        self.line("});"); // close STATE.with
        self.indent -= 1;
        self.line("}");
        self.line("");

        // Handler functions
        for (i, method) in comp.methods.iter().enumerate() {
            self.emit_handler(name, method, i);
        }
    }

    fn emit_template_node(&mut self, node: &TemplateNode, parent_var: &str, comp_name: &str) {
        match node {
            TemplateNode::Element(el) => {
                let var = format!("el_{}", self.fresh_id());
                self.last_element_var = var.clone();
                self.line(&format!("let {} = tree.create(\"{}\");", var, el.tag));
                self.line(&format!("tree.append_child({}, {});", parent_var, var));

                // Attributes
                for attr in &el.attributes {
                    match attr {
                        Attribute::Static { name, value } => {
                            if name == "style" {
                                // Parse inline style string into individual set_style calls
                                for part in value.split(';') {
                                    let part = part.trim();
                                    if let Some((prop, val)) = part.split_once(':') {
                                        let prop = prop.trim();
                                        let val = val.trim();
                                        self.line(&format!("tree.set_style({}, \"{}\", \"{}\");", var, prop, val));
                                    }
                                }
                            } else if name == "placeholder" {
                                self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.placeholder = Some(\"{}\".into()); }}", var, value));
                            } else if name == "pill" {
                                // Register category pill for active state styling
                                self.line(&format!("honeycomb::canvas_app::register_pill(\"{}\".as_ptr(), {}, {});", value, value.len(), var));
                            }
                        }
                        Attribute::Dynamic { name, value } => {
                            let val_rust = self.expr_to_rust(value, comp_name);
                            if name == "style" {
                                // Dynamic style — value is a runtime string expression
                                // Parse it at runtime by splitting on semicolons
                                self.line(&format!("{{ let _style_val = {}; for _part in _style_val.split(';') {{ let _part = _part.trim(); if let Some((_p, _v)) = _part.split_once(':') {{ tree.set_style({}, _p.trim(), _v.trim()); }} }} }}", val_rust, var));
                            } else {
                                // Dynamic attribute — set as attribute (borrow to avoid move)
                                self.line(&format!("tree.set_attribute({}, \"{}\", &{});", var, name, val_rust));
                                // Register filterable elements for O(n) filter toggle
                                if name == "category" {
                                    self.line(&format!("honeycomb::canvas_app::register_filter_card({}, {}.as_ptr(), {}.len() as u32);", var, val_rust, val_rust));
                                }
                            }
                        }
                        Attribute::EventHandler { event, handler } => {
                            if event == "click" {
                                if let Some(method_name) = self.extract_handler_name(handler) {
                                    let idx = self.handler_indices.get(&method_name).copied().unwrap_or(0);
                                    self.line(&format!("// on:click -> {} (cb_idx={})", method_name, idx));
                                    self.line(&format!("tree.add_event({}, \"click\", {});", var, idx));
                                    // Clickable elements get pointer cursor + focusable (hover/active states)
                                    self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.visual.cursor = 1; el.focusable = true; }}", var));
                                }
                            }
                        }
                        Attribute::Bind { property, signal } => {
                            // Two-way binding — read value from state, set on element
                            self.line(&format!("{{ let _bind_val = {}; if let Some(el) = tree.get_mut({}) {{ el.set_prop(\"{}\", &format!(\"{{}}\", _bind_val)); }} }}",
                                signal, var, property));
                        }
                        Attribute::Aria { name, value } => {
                            let val_rust = self.expr_to_rust(value, comp_name);
                            self.line(&format!("// aria-{} = {}", name, val_rust));
                        }
                        Attribute::Role { value } => {
                            self.line(&format!("// role = {}", value));
                        }
                    }
                }

                // Children — optimize: if single text/expression child, inline on parent element
                if el.children.len() == 1 {
                    match &el.children[0] {
                        TemplateNode::TextLiteral(text) => {
                            let escaped = text.replace('\\', "\\\\").replace('"', "\\\"");
                            self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.text = Some(\"{}\".into()); }}", var, escaped));
                        }
                        TemplateNode::Expression(expr) => {
                            let rust_expr = self.expr_to_rust(expr, comp_name);
                            self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.text = Some({}.to_string()); }}", var, rust_expr));
                            // Register metric text nodes
                            let field_name = match &**expr {
                                Expr::FieldAccess { object, field } if matches!(**object, Expr::SelfExpr) => Some(field.clone()),
                                Expr::FnCall { callee, args } => {
                                    if let Expr::Ident(name) = &**callee {
                                        if name == "format" && args.len() == 2 {
                                            if let Expr::FieldAccess { object, field } = &args[1] {
                                                if matches!(**object, Expr::SelfExpr) { Some(field.clone()) } else { None }
                                            } else { None }
                                        } else { None }
                                    } else { None }
                                }
                                _ => None,
                            };
                            if let Some(field) = field_name {
                                self.line(&format!("honeycomb::canvas_app::register_metric_text(\"{}\".as_ptr(), {}, {});", field, field.len(), var));
                            }
                        }
                        _ => {
                            self.emit_template_node(&el.children[0], &var, comp_name);
                        }
                    }
                } else {
                    for child in &el.children {
                        self.emit_template_node(child, &var, comp_name);
                    }
                }
            }
            TemplateNode::TextLiteral(text) => {
                let var = format!("txt_{}", self.fresh_id());
                self.line(&format!("let {} = tree.create(\"#text\");", var));
                self.line(&format!("tree.append_child({}, {});", parent_var, var));
                // Escape quotes in text
                let escaped = text.replace('\\', "\\\\").replace('"', "\\\"");
                self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.text = Some(\"{}\".into()); }}", var, escaped));
            }
            TemplateNode::Expression(expr) => {
                // Dynamic text — read from component state
                let var = format!("dyn_{}", self.fresh_id());
                self.line(&format!("let {} = tree.create(\"#text\");", var));
                self.line(&format!("tree.append_child({}, {});", parent_var, var));
                let rust_expr = self.expr_to_rust(expr, comp_name);
                self.line(&format!("if let Some(el) = tree.get_mut({}) {{ el.text = Some({}.to_string()); }}", var, rust_expr));
                // Register metric text nodes for direct updates without tree rebuild
                // Handles {self.field} and {format("{}", self.field)}
                let field_name = match &**expr {
                    Expr::FieldAccess { object, field } if matches!(**object, Expr::SelfExpr) => {
                        Some(field.clone())
                    }
                    Expr::FnCall { callee, args } => {
                        // format("{}", self.field) → register as "field"
                        if let Expr::Ident(name) = &**callee {
                            if name == "format" && args.len() == 2 {
                                if let Expr::FieldAccess { object, field } = &args[1] {
                                    if matches!(**object, Expr::SelfExpr) {
                                        Some(field.clone())
                                    } else { None }
                                } else { None }
                            } else { None }
                        } else { None }
                    }
                    _ => None,
                };
                if let Some(field) = field_name {
                    self.line(&format!("honeycomb::canvas_app::register_metric_text(\"{}\".as_ptr(), {}, {});",
                        field, field.len(), var));
                }
            }
            TemplateNode::Fragment(children) => {
                for child in children {
                    self.emit_template_node(child, parent_var, comp_name);
                }
            }
            TemplateNode::TemplateFor { binding, iterator, children, .. } => {
                let iter_rust = self.expr_to_rust(iterator, comp_name);
                if iter_rust.contains("..") {
                    self.line(&format!("for {} in {} {{", binding, iter_rust));
                } else {
                    self.line(&format!("for {} in {}.iter() {{", binding, iter_rust));
                }
                self.indent += 1;

                // Check if children contain a TemplateIf that matches a filter pattern.
                // If so, skip the {if} (render all items) and auto-register for filtering.
                let filter_for_this_loop = self.filter_patterns.iter().find(|fp| {
                    children.iter().any(|c| matches!(c, TemplateNode::TemplateIf { .. }))
                }).cloned();

                for child in children {
                    if let (Some(fp), TemplateNode::TemplateIf { then_children, .. }) = (&filter_for_this_loop, child) {
                        // Emit the then_children directly (skip the {if} — all items rendered)
                        // Auto-register the first element for filtering
                        for (ci, tc) in then_children.iter().enumerate() {
                            self.emit_template_node(tc, parent_var, comp_name);
                            // After the first element child, auto-register it for filtering
                            if ci == 0 {
                                if let TemplateNode::Element(_) = tc {
                                    let card_var = self.last_element_var.clone();
                                    let filter_val = format!("{}.{}", binding, fp.item_field);
                                    self.line(&format!("// Auto-detected filter pattern: register for O(n) filtering"));
                                    self.line(&format!("tree.set_attribute({}, \"{}\", &{});", card_var, fp.item_field, filter_val));
                                    self.line(&format!("honeycomb::canvas_app::register_filter_card({}, {}.as_ptr(), {}.len() as u32);", card_var, filter_val, filter_val));
                                }
                            }
                        }
                    } else {
                        self.emit_template_node(child, parent_var, comp_name);
                    }
                }
                self.indent -= 1;
                self.line("}");
            }
            TemplateNode::TemplateIf { condition, then_children, else_children } => {
                let cond_rust = self.expr_to_rust(condition, comp_name);
                self.line(&format!("if {} {{", cond_rust));
                self.indent += 1;
                for child in then_children {
                    self.emit_template_node(child, parent_var, comp_name);
                }
                self.indent -= 1;
                if let Some(else_nodes) = else_children {
                    self.line("} else {");
                    self.indent += 1;
                    for child in else_nodes {
                        self.emit_template_node(child, parent_var, comp_name);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            _ => {} // Link, Outlet, Layout, TemplateMatch not yet supported
        }
    }

    fn emit_handler(&mut self, comp_name: &str, method: &Function, _idx: usize) {
        let is_init = method.name.starts_with("init");

        self.line(&format!("fn {}_{}() {{", comp_name.to_lowercase(), method.name));
        self.indent += 1;

        // Time the entire handler cycle (state update + tree rebuild + layout)
        if !is_init {
            self.line("let _op_t0 = perf_now();");
        }

        self.line(&format!("{}_STATE.with(|s| {{", comp_name.to_uppercase()));
        self.indent += 1;
        self.line("let mut state = s.borrow_mut();");
        self.in_handler = true;

        // Emit method body
        for stmt in &method.body.stmts {
            self.emit_stmt(stmt, comp_name);
        }

        self.in_handler = false;
        self.indent -= 1;
        self.line("});");

        // Init methods don't re-render — they're called before first mount
        if !is_init {
            // Auto-detect filter handlers by matching handler body against template patterns.
            // If a handler only assigns to a state field that controls a {if} inside a {for},
            // use O(n) display_none toggle instead of full tree rebuild.
            let filter_match = self.filter_patterns.iter().find(|fp| {
                self.handler_only_sets_field(method, &fp.state_field)
            }).cloned();
            let is_sort = method.body.stmts.iter().any(|s| {
                let dbg = format!("{:?}", s);
                dbg.contains("sort_asc") || dbg.contains("sort_desc") || dbg.contains("sort_str")
            });
            if let Some(ref fp) = filter_match {
                self.line("// O(n) filter: auto-detected from template {if} pattern");
                self.line(&format!("let _fv = {}_STATE.with(|s| s.borrow().{}.clone());", comp_name.to_uppercase(), fp.state_field));
                self.line("honeycomb::canvas_app::apply_filter(&_fv);");
            } else if is_sort {
                // Sort already called apply_sort_permutation inline via .sort_asc/.sort_desc
                // No tree rebuild needed — just update metrics
            } else {
                self.line("// Re-render after state change");
                self.line("with_tree(|tree| {");
                self.indent += 1;
                self.line("let root = tree.root_id();");
                self.line("if let Some(el) = tree.get_mut(root) { el.children.clear(); }");
                self.indent -= 1;
                self.line("});");
                self.line(&format!("{}_mount();", comp_name.to_lowercase()));
                self.line("render();");
            }
            // Record total handler time + update text node
            self.line("let _op_elapsed = to_ms_string(_op_t0, perf_now());");
            self.line(&format!("{}_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());",
                comp_name.to_uppercase()));
            self.line("update_metric_text(\"last_op_ms\", &_op_elapsed);");

            // For data-loaded callbacks, also update total_ms to show full pipeline time
            if method.name.contains("loaded") || method.name.contains("response") {
                self.line("// Full pipeline time: init → fetch → parse → render");
                self.line("let _total = to_ms_string(unsafe { INIT_START }, perf_now());");
                self.line(&format!("{}_STATE.with(|s| s.borrow_mut().total_ms = _total.clone());",
                    comp_name.to_uppercase()));
                self.line("update_metric_text(\"total_ms\", &_total);");
                // Also update product count
                self.line(&format!("let _pc = {}_STATE.with(|s| format!(\"{{}}\", s.borrow().product_count));",
                    comp_name.to_uppercase()));
                self.line("update_metric_text(\"product_count\", &_pc);");
            }
        }

        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_stmt(&mut self, stmt: &Stmt, comp_name: &str) {
        match stmt {
            Stmt::Expr(Expr::Assign { target, value }) => {
                let target_rust = self.expr_to_rust(target, comp_name);
                let mut value_rust = self.expr_to_rust(value, comp_name);
                // String literal assigned to a String variable needs .to_string()
                if value_rust.starts_with('"') {
                    value_rust = format!("{}.to_string()", value_rust);
                }
                self.line(&format!("{} = {};", target_rust, value_rust));
            }
            Stmt::Expr(Expr::While { condition, body }) => {
                let cond = self.expr_to_rust(condition, comp_name);
                self.line(&format!("while {} {{", cond));
                self.indent += 1;
                for s in &body.stmts {
                    self.emit_stmt(s, comp_name);
                }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Expr(Expr::For { binding, iterator, body }) => {
                let iter = self.expr_to_rust(iterator, comp_name);
                self.line(&format!("for {} in {} {{", binding, iter));
                self.indent += 1;
                for s in &body.stmts {
                    self.emit_stmt(s, comp_name);
                }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Expr(Expr::If { condition, then_block, else_block }) => {
                let cond = self.expr_to_rust(condition, comp_name);
                self.line(&format!("if {} {{", cond));
                self.indent += 1;
                for s in &then_block.stmts {
                    self.emit_stmt(s, comp_name);
                }
                self.indent -= 1;
                if let Some(else_blk) = else_block {
                    self.line("} else {");
                    self.indent += 1;
                    for s in &else_blk.stmts {
                        self.emit_stmt(s, comp_name);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::Expr(expr) => {
                let e = self.expr_to_rust(expr, comp_name);
                self.line(&format!("{};", e));
            }
            Stmt::Return(Some(expr)) => {
                let e = self.expr_to_rust(expr, comp_name);
                self.line(&format!("return {};", e));
            }
            Stmt::Return(None) => {
                self.line("return;");
            }
            Stmt::Let { name, value, mutable, ty, .. } => {
                let mut val = self.expr_to_rust(value, comp_name);
                // String fields initialized from string literals need .to_string()
                let is_string_type = ty.as_ref().map(|t| self.type_to_rust(t) == "String").unwrap_or(false);
                if is_string_type && val.starts_with('"') {
                    val = format!("{}.to_string()", val);
                }
                if *mutable {
                    self.line(&format!("let mut {} = {};", name, val));
                } else {
                    self.line(&format!("let {} = {};", name, val));
                }
            }
            _ => {
                self.line("// TODO: unsupported statement");
            }
        }
    }

    fn expr_to_rust(&self, expr: &Expr, comp_name: &str) -> String {
        match expr {
            Expr::Integer(n) => format!("{}", n),
            Expr::Float(f) => format!("{:.1}", f),
            Expr::StringLit(s) => format!("\"{}\"", s),
            Expr::Bool(b) => format!("{}", b),
            Expr::Ident(name) => {
                if name.starts_with("self.") {
                    format!("{}_STATE.with(|s| s.borrow().{})", comp_name.to_uppercase(), &name[5..])
                } else {
                    name.clone()
                }
            }
            Expr::SelfExpr => {
                if self.in_handler { "state".to_string() } else { "self".to_string() }
            }
            Expr::FieldAccess { object, field } => {
                // self.field →
                //   handler: state.field (inside STATE.with closure)
                //   render:  field (local variable extracted before with_tree)
                if matches!(**object, Expr::SelfExpr) {
                    if self.in_handler {
                        format!("state.{}", field)
                    } else {
                        field.clone() // local variable
                    }
                } else {
                    let obj = self.expr_to_rust(object, comp_name);
                    format!("{}.{}", obj, field)
                }
            }
            Expr::Binary { left, op, right } => {
                let l = self.expr_to_rust(left, comp_name);
                let r = self.expr_to_rust(right, comp_name);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::Neq => "!=",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::Lte => "<=",
                    BinOp::Gte => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FnCall { callee, args } => {
                let callee_str = self.expr_to_rust(callee, comp_name);
                if callee_str == "format" && !args.is_empty() {
                    // format("...", arg1, arg2) → format!("...", arg1, arg2)
                    let fmt = self.expr_to_rust(&args[0], comp_name);
                    let rest: Vec<String> = args[1..].iter().map(|a| self.expr_to_rust(a, comp_name)).collect();
                    if rest.is_empty() {
                        format!("format!({})", fmt)
                    } else {
                        format!("format!({}, {})", fmt, rest.join(", "))
                    }
                } else {
                    let a: Vec<String> = args.iter().map(|a| self.expr_to_rust(a, comp_name)).collect();
                    format!("{}({})", callee_str, a.join(", "))
                }
            }
            Expr::MethodCall { object, method, args } => {
                let obj = self.expr_to_rust(object, comp_name);
                let a: Vec<String> = args.iter().map(|a| self.expr_to_rust(a, comp_name)).collect();
                if method == "cmp" && a.len() == 1 && !a[0].starts_with('&') {
                    format!("{}.cmp(&{})", obj, a[0])
                } else if method == "len" {
                    format!("{}.len() as i32", obj)
                } else if method == "swap" && a.len() == 2 {
                    // .swap() takes usize indices — auto-cast from i32
                    format!("{}.swap({} as usize, {} as usize)", obj, a[0], a[1])
                } else if method == "contains" && a.len() == 1 {
                    // .contains() on String takes &str — auto-borrow
                    format!("{}.contains(&{})", obj, a[0])
                } else if method == "sort_asc" && a.len() == 1 {
                    let field = a[0].trim_matches('"');
                    format!("{{ let _k: Vec<i32> = {obj}.iter().map(|p| p.{field} as i32).collect(); honeycomb::canvas_app::apply_sort_by_i32(&_k, true); }}", obj=obj, field=field)
                } else if method == "sort_desc" && a.len() == 1 {
                    let field = a[0].trim_matches('"');
                    format!("{{ let _k: Vec<i32> = {obj}.iter().map(|p| p.{field} as i32).collect(); honeycomb::canvas_app::apply_sort_by_i32(&_k, false); }}", obj=obj, field=field)
                } else if method == "sort_str_asc" && a.len() == 1 {
                    // Argsort by string field — sort indices in-place, no string cloning
                    let field = a[0].trim_matches('"');
                    format!("{{ let mut _idx: Vec<u32> = (0..{obj}.len() as u32).collect(); _idx.sort_unstable_by(|&a, &b| {obj}[a as usize].{field}.cmp(&{obj}[b as usize].{field})); honeycomb::canvas_app::apply_sort_by_indices(&_idx); }}", obj=obj, field=field)
                } else if method == "sort_str_desc" && a.len() == 1 {
                    let field = a[0].trim_matches('"');
                    format!("{{ let mut _idx: Vec<u32> = (0..{obj}.len() as u32).collect(); _idx.sort_unstable_by(|&a, &b| {obj}[b as usize].{field}.cmp(&{obj}[a as usize].{field})); honeycomb::canvas_app::apply_sort_by_indices(&_idx); }}", obj=obj, field=field)
                } else if method == "reverse" {
                    format!("{}.reverse()", obj)
                } else {
                    format!("{}.{}({})", obj, method, a.join(", "))
                }
            }
            Expr::Range { start, end } => {
                let s = self.expr_to_rust(start, comp_name);
                let e = self.expr_to_rust(end, comp_name);
                format!("{}..{}", s, e)
            }
            Expr::ArrayLit(items) => {
                let elems: Vec<String> = items.iter().map(|e| self.expr_to_rust(e, comp_name)).collect();
                format!("vec![{}]", elems.join(", "))
            }
            Expr::Unary { op, operand } => {
                let o = self.expr_to_rust(operand, comp_name);
                match op {
                    UnaryOp::Neg => format!("(-{})", o),
                    UnaryOp::Not => format!("(!{})", o),
                }
            }
            Expr::Index { object, index } => {
                let obj = self.expr_to_rust(object, comp_name);
                let idx = self.expr_to_rust(index, comp_name);
                format!("{}[{} as usize]", obj, idx)
            }
            Expr::Assign { target, value } => {
                let t = self.expr_to_rust(target, comp_name);
                let v = self.expr_to_rust(value, comp_name);
                format!("{} = {}", t, v)
            }
            Expr::StructInit { name, fields } => {
                let field_strs: Vec<String> = fields.iter().map(|(fname, fval)| {
                    let v = self.expr_to_rust(fval, comp_name);
                    // String literal values in struct init need .to_string() for String fields
                    if v.starts_with('"') {
                        format!("{}: {}.to_string()", fname, v)
                    } else {
                        format!("{}: {}", fname, v)
                    }
                }).collect();
                format!("{} {{ {} }}", name, field_strs.join(", "))
            }
            Expr::Closure { params, body } => {
                let p: Vec<String> = params.iter().map(|(name, ty)| {
                    if let Some(t) = ty {
                        format!("{}: {}", name, self.type_to_rust(t))
                    } else {
                        name.clone()
                    }
                }).collect();
                let b = self.expr_to_rust(body, comp_name);
                format!("|{}| {{ {} }}", p.join(", "), b)
            }
            Expr::Block(block) => {
                let stmts: Vec<String> = block.stmts.iter().map(|s| {
                    match s {
                        Stmt::Expr(e) => self.expr_to_rust(e, comp_name),
                        Stmt::Let { name, value, mutable, .. } => {
                            let val = self.expr_to_rust(value, comp_name);
                            if *mutable {
                                format!("let mut {} = {}", name, val)
                            } else {
                                format!("let {} = {}", name, val)
                            }
                        }
                        Stmt::Return(Some(e)) => format!("return {}", self.expr_to_rust(e, comp_name)),
                        Stmt::Return(None) => "return".to_string(),
                        _ => "()".to_string(),
                    }
                }).collect();
                if stmts.len() == 1 {
                    stmts[0].clone()
                } else {
                    format!("{{ {} }}", stmts.join("; "))
                }
            }
            Expr::If { condition, then_block, else_block } => {
                let cond = self.expr_to_rust(condition, comp_name);
                let then_stmts: Vec<String> = then_block.stmts.iter().map(|s| {
                    match s { Stmt::Expr(e) => self.expr_to_rust(e, comp_name), _ => "()".into() }
                }).collect();
                let then_str = then_stmts.last().cloned().unwrap_or("()".into());
                if let Some(else_blk) = else_block {
                    let else_stmts: Vec<String> = else_blk.stmts.iter().map(|s| {
                        match s { Stmt::Expr(e) => self.expr_to_rust(e, comp_name), _ => "()".into() }
                    }).collect();
                    let else_str = else_stmts.last().cloned().unwrap_or("()".into());
                    format!("if {} {{ {} }} else {{ {} }}", cond, then_str, else_str)
                } else {
                    format!("if {} {{ {} }}", cond, then_str)
                }
            }
            _ => "/* unsupported expr */".to_string(),
        }
    }

    fn emit_main(&mut self, program: &Program) {
        // Find the first component
        let comp_name = program.items.iter().find_map(|item| {
            if let Item::Component(c) = item { Some(c.name.clone()) } else { None }
        }).unwrap_or_else(|| "App".to_string());

        self.line("// ── Render: layout only (painting done by Honeycomb's app_render) ──");
        self.line("");
        self.line("fn render() {");
        self.indent += 1;
        self.line("honeycomb::wasm_api::TREE.with(|t| {");
        self.indent += 1;
        self.line("let mut tree = t.borrow_mut();");
        self.line("let mut measurer = EstimateMeasurer;");
        self.line("let vw = unsafe { canvas_get_width() };");
        self.line("let vh = unsafe { canvas_get_height() };");
        self.line("layout::compute(&mut tree, vw, vh, &mut measurer);");
        self.indent -= 1;
        self.line("});");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // WASM export — builds the element tree in Honeycomb's wasm_api TREE.
        // Called BEFORE app_init so Honeycomb detects the pre-built tree.
        // Check if the component has init methods (init_*, or just init)
        let comp = program.items.iter().find_map(|item| {
            if let Item::Component(c) = item { Some(c) } else { None }
        });
        let init_methods: Vec<String> = comp.map(|c| {
            c.methods.iter()
                .filter(|m| m.name.starts_with("init"))
                .map(|m| format!("{}_{}", comp_name.to_lowercase(), m.name))
                .collect()
        }).unwrap_or_default();

        // Check if there's an init method that triggers a fetch (init_data, init_load, etc.)
        // and a corresponding on_*_loaded callback
        let has_fetch_init = comp.as_ref().map(|c| {
            c.methods.iter().any(|m| m.name.starts_with("init_data") || m.name.starts_with("init_load"))
        }).unwrap_or(false);

        let fetch_callback_idx = comp.as_ref().and_then(|c| {
            let non_init: Vec<&str> = c.methods.iter()
                .filter(|m| !m.name.starts_with("init"))
                .map(|m| m.name.as_str())
                .collect();
            non_init.iter().position(|n| n.contains("loaded") || n.contains("response"))
        });

        self.line("#[no_mangle]");
        self.line(&format!("pub extern \"C\" fn nectar_init(_vw: f32, _vh: f32) {{"));
        self.indent += 1;
        self.line("let _init_t0 = perf_now();");
        self.line("unsafe { INIT_START = _init_t0; }");
        for init_fn in &init_methods {
            self.line(&format!("{}();", init_fn));
        }
        self.line(&format!("{}_mount();", comp_name.to_lowercase()));
        // Record total init time (heap + mount) + update text node
        self.line("let _init_elapsed = to_ms_string(_init_t0, perf_now());");
        self.line(&format!("{}_STATE.with(|s| s.borrow_mut().total_ms = _init_elapsed.clone());",
            comp_name.to_uppercase()));
        self.line("update_metric_text(\"total_ms\", &_init_elapsed);");
        // Also update heap_ms text node
        self.line(&format!("let _heap = {}_STATE.with(|s| s.borrow().heap_ms.clone());", comp_name.to_uppercase()));
        self.line("update_metric_text(\"heap_ms\", &_heap);");

        // Auto-fetch if init_data/init_load exists with a matching on_*_loaded callback
        if has_fetch_init {
            if let Some(cb_idx) = fetch_callback_idx {
                self.line("// Auto-fetch: init_data detected, firing fetch with callback");
                self.line(&format!("fetch_get(\"/api/products?per_page=10000\", {});", cb_idx));
            }
        }

        self.indent -= 1;
        self.line("}");
        self.line("");

        // Callback dispatcher — called by JS when async operations complete (fetch, timers)
        // Each handler method gets a callback index. The __callback export dispatches by index.
        if let Some(comp) = comp {
            let handlers: Vec<&str> = comp.methods.iter()
                .filter(|m| !m.name.starts_with("init"))
                .map(|m| m.name.as_str())
                .collect();
            if !handlers.is_empty() {
                self.line("#[no_mangle]");
                self.line("pub extern \"C\" fn __callback(idx: u32) {");
                self.indent += 1;

                // For fetch callbacks, parse JSON response before calling handler
                if let Some(cb_idx) = fetch_callback_idx {
                    self.line(&format!("if idx == {} {{", cb_idx));
                    self.indent += 1;
                    self.line("// Parse fetch response as JSON into component state");
                    self.line("let _t_copy = perf_now();");
                    self.line("let (_status, body) = read_response();");
                    self.line("let _t_copied = perf_now();");
                    self.line(&format!("{}_STATE.with(|s| {{", comp_name.to_uppercase()));
                    self.indent += 1;
                    self.line("let mut state = s.borrow_mut();");
                    // Find the first Vec<StructType> field and deserialize into it
                    for field in &comp.state {
                        if let Some(ref ty) = field.ty {
                            let ty_str = self.type_to_rust(ty);
                            if ty_str.starts_with("Vec<") && !ty_str.contains("i32") && !ty_str.contains("f32") && !ty_str.contains("bool") && !ty_str.contains("String") {
                                self.line(&format!("if let Ok(parsed) = serde_json::from_slice::<{}>(&body) {{", ty_str));
                                self.indent += 1;
                                self.line(&format!("state.{} = parsed;", field.name));
                                self.indent -= 1;
                                self.line("}");
                            }
                        }
                    }
                    self.indent -= 1;
                    self.line("});");
                    self.line("let _t_parsed = perf_now();");
                    // Log timing breakdown
                    self.line("{");
                    self.indent += 1;
                    self.line("let msg = format!(\"FETCH BREAKDOWN: copy={:.2}ms serde_parse={:.2}ms body={}bytes\", _t_copied - _t_copy, _t_parsed - _t_copied, body.len());");
                    self.line("unsafe { console_log(msg.as_ptr(), msg.len() as u32); }");
                    self.indent -= 1;
                    self.line("}");
                    self.indent -= 1;
                    self.line("}");
                }

                self.line("match idx {");
                self.indent += 1;
                for (i, name) in handlers.iter().enumerate() {
                    self.line(&format!("{} => {}_{}(),", i, comp_name.to_lowercase(), name));
                }
                self.line("_ => {}");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
        }
    }

    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Named(name) => {
                match name.as_str() {
                    "i32" => "i32".into(),
                    "i64" => "i64".into(),
                    "f32" => "f32".into(),
                    "f64" => "f64".into(),
                    "bool" => "bool".into(),
                    "String" | "string" => "String".into(),
                    other => other.to_string(),
                }
            }
            Type::Array(inner) => format!("Vec<{}>", self.type_to_rust(inner)),
            Type::Option(inner) => format!("Option<{}>", self.type_to_rust(inner)),
            Type::Result { ok, err } => format!("Result<{}, {}>", self.type_to_rust(ok), self.type_to_rust(err)),
            Type::Tuple(types) => {
                let parts: Vec<String> = types.iter().map(|t| self.type_to_rust(t)).collect();
                format!("({})", parts.join(", "))
            }
            Type::Generic { name, args } => {
                let parts: Vec<String> = args.iter().map(|t| self.type_to_rust(t)).collect();
                format!("{}<{}>", name, parts.join(", "))
            }
            Type::Reference { mutable, inner, .. } => {
                if *mutable {
                    format!("&mut {}", self.type_to_rust(inner))
                } else {
                    format!("&{}", self.type_to_rust(inner))
                }
            }
            Type::Function { params, ret } => {
                let p: Vec<String> = params.iter().map(|t| self.type_to_rust(t)).collect();
                format!("fn({}) -> {}", p.join(", "), self.type_to_rust(ret))
            }
        }
    }

    fn extract_handler_name(&self, expr: &Expr) -> Option<String> {
        match expr {
            Expr::FieldAccess { field, .. } => Some(field.clone()),
            Expr::MethodCall { method, .. } => Some(method.clone()),
            Expr::Ident(name) => Some(name.clone()),
            _ => None,
        }
    }

    fn fresh_id(&self) -> u32 {
        use std::sync::atomic::{AtomicU32, Ordering};
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        COUNTER.fetch_add(1, Ordering::Relaxed)
    }
}
