use crate::ast::*;
use crate::critical_css::CriticalCssResult;

/// Server-Side Rendering codegen for Nectar components.
///
/// Emits a Node.js-compatible JavaScript module that renders Nectar components
/// to HTML strings on the server. The generated module exports a `render`
/// function per component and a top-level `renderApp` that produces a
/// full HTML document with serialized state for client-side hydration.
pub struct SsrCodegen {
    output: String,
    indent: usize,
    /// Counter for generating unique hydration keys
    key_counter: u32,
    /// Optional critical CSS data — when present, inlined into SSR output
    critical_css: Option<CriticalCssResult>,
}

impl SsrCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            key_counter: 0,
            critical_css: None,
        }
    }

    /// Create an SSR codegen instance with critical CSS extraction results.
    /// When present, the generated SSR module will inline critical styles in
    /// `<head>` and emit an async loader for deferred styles.
    pub fn with_critical_css(css_result: CriticalCssResult) -> Self {
        Self {
            output: String::new(),
            indent: 0,
            key_counter: 0,
            critical_css: Some(css_result),
        }
    }

    /// Returns the deferred CSS content (if critical CSS extraction was used).
    /// This is written to a separate `.css` file by the compiler driver.
    pub fn deferred_css_content(&self) -> Option<String> {
        self.critical_css.as_ref().map(|c| c.deferred_css.clone())
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.line("// Nectar SSR Module — auto-generated by the Nectar compiler");
        self.line("// This module renders Nectar components to HTML strings on the server.");
        self.line("'use strict';");
        self.line("");
        self.line("const { Readable } = require('stream');");
        self.line("");

        // Emit HTML escape utility
        self.emit_escape_util();

        // Emit store state collector
        self.line("const __nectarState = {};");
        self.line("");

        // Process all items
        for item in &program.items {
            match item {
                Item::Store(store) => self.generate_store(store),
                Item::Component(comp) => self.generate_component(comp),
                Item::Router(router) => self.generate_router(router),
                Item::LazyComponent(lazy) => self.generate_component(&lazy.component),
                _ => {}
            }
        }

        // Emit the state serialization helper
        self.line("");
        self.line("function __serializeState() {");
        self.indent += 1;
        self.line("return '<script>window.__NECTAR_STATE__ = ' + JSON.stringify(__nectarState) + '</script>';");
        self.indent -= 1;
        self.line("}");

        // Emit critical CSS helpers if critical CSS extraction was used
        if self.critical_css.is_some() {
            // Clone CSS strings to avoid borrow conflict with self.line()
            let skeleton_css = self.critical_css.as_ref().unwrap().skeleton_css.clone();
            let critical_css = self.critical_css.as_ref().unwrap().critical_css.clone();

            self.line("");
            self.line("// --- Critical CSS (inlined by nectar build --critical-css) ---");
            self.line("");

            // Emit the critical CSS string constant
            let escaped_skeleton = skeleton_css
                .replace('\\', "\\\\")
                .replace('\'', "\\'")
                .replace('\n', "\\n");
            let escaped_critical = critical_css
                .replace('\\', "\\\\")
                .replace('\'', "\\'")
                .replace('\n', "\\n");

            self.line(&format!(
                "const __nectarSkeletonCss = '{}';",
                escaped_skeleton
            ));
            self.line(&format!(
                "const __nectarCriticalCss = '{}';",
                escaped_critical
            ));
            self.line("");

            self.line("function __criticalStyleTag() {");
            self.indent += 1;
            self.line("return '<style data-nectar-critical>' + __nectarSkeletonCss + '\\n' + __nectarCriticalCss + '</style>';");
            self.indent -= 1;
            self.line("}");
            self.line("");

            self.line("function __deferredStyleLink() {");
            self.indent += 1;
            self.line("return '<link rel=\"stylesheet\" href=\"styles.css\" media=\"print\" onload=\"this.media=\\'all\\'\">' +");
            self.line("  '<noscript><link rel=\"stylesheet\" href=\"styles.css\"></noscript>';");
            self.indent -= 1;
            self.line("}");
            self.line("");

            self.line("function __criticalLoadedScript() {");
            self.indent += 1;
            self.line("return '<script>window.__nectarCriticalLoaded = true;</script>';");
            self.indent -= 1;
            self.line("}");
        }

        // Emit the top-level renderApp export
        self.line("");
        self.line("function renderApp(componentName, props, url) {");
        self.indent += 1;
        self.line("const renderFn = module.exports['render_' + componentName];");
        self.line("if (!renderFn) throw new Error('Unknown component: ' + componentName);");
        self.line("const html = renderFn(props || {});");

        if self.critical_css.is_some() {
            self.line("return __criticalStyleTag() + html + __serializeState() + __deferredStyleLink() + __criticalLoadedScript();");
        } else {
            self.line("return html + __serializeState();");
        }

        self.indent -= 1;
        self.line("}");

        // Emit stream rendering helper
        self.line("");
        self.line("function renderToStream(componentName, props, url) {");
        self.indent += 1;
        self.line("const html = renderApp(componentName, props, url);");
        self.line("const stream = new Readable({");
        self.indent += 1;
        self.line("read() {");
        self.indent += 1;
        self.line("this.push(html);");
        self.line("this.push(null);");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("});");
        self.line("return stream;");
        self.indent -= 1;
        self.line("}");

        // Module exports
        self.line("");
        self.line("module.exports.renderApp = renderApp;");
        self.line("module.exports.renderToStream = renderToStream;");
        self.line("module.exports.__serializeState = __serializeState;");

        if self.critical_css.is_some() {
            self.line("module.exports.__criticalStyleTag = __criticalStyleTag;");
            self.line("module.exports.__deferredStyleLink = __deferredStyleLink;");
            self.line("module.exports.__criticalLoadedScript = __criticalLoadedScript;");
        }

        self.output.clone()
    }

    fn emit_escape_util(&mut self) {
        self.line("function __escapeHtml(str) {");
        self.indent += 1;
        self.line("if (str == null) return '';");
        self.line("return String(str)");
        self.indent += 1;
        self.line(".replace(/&/g, '&amp;')");
        self.line(".replace(/</g, '&lt;')");
        self.line(".replace(/>/g, '&gt;')");
        self.line(".replace(/\"/g, '&quot;')");
        self.line(".replace(/'/g, '&#x27;');");
        self.indent -= 1;
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn generate_store(&mut self, store: &StoreDef) {
        let store_name = &store.name;
        self.line(&format!("// === Store: {} ===", store_name));

        // Initialize store state object
        self.line(&format!("__nectarState['{}'] = {{}};", store_name));

        // Generate init function that populates initial signal values
        self.line(&format!("function __initStore_{}() {{", store_name));
        self.indent += 1;

        for sig in &store.signals {
            let init_val = self.expr_to_js(&sig.initializer);
            self.line(&format!(
                "__nectarState['{}']['{}'] = {};",
                store_name, sig.name, init_val
            ));
        }

        self.indent -= 1;
        self.line("}");
        self.line(&format!("__initStore_{}();", store_name));

        // Generate getters for computed values (simplified: return initial value)
        for comp in &store.computed {
            self.line(&format!(
                "function __store_{}_get_{}() {{",
                store_name, comp.name
            ));
            self.indent += 1;
            self.line(&format!(
                "return __nectarState['{}']['{}'];",
                store_name, comp.name
            ));
            self.indent -= 1;
            self.line("}");
        }

        self.line("");
    }

    fn generate_component(&mut self, comp: &Component) {
        let comp_name = &comp.name;
        self.line(&format!("// === Component: {} ===", comp_name));

        self.line(&format!("function render_{}(props) {{", comp_name));
        self.indent += 1;

        // Initialize props with defaults
        for prop in &comp.props {
            let default_val = if let Some(ref default) = prop.default {
                self.expr_to_js(default)
            } else {
                "undefined".to_string()
            };
            self.line(&format!(
                "const {} = props['{}'] !== undefined ? props['{}'] : {};",
                prop.name, prop.name, prop.name, default_val
            ));
        }

        // Initialize state to initial values (no reactivity on server)
        for state in &comp.state {
            let init_val = self.expr_to_js(&state.initializer);
            self.line(&format!("const {} = {};", state.name, init_val));
        }

        // Generate the render template as HTML string concatenation
        self.line("let __html = '';");

        // If the component has a skeleton, render it with a data-nectar-skeleton marker
        // so the client can identify and replace it during hydration
        if let Some(ref skel) = comp.skeleton {
            self.line("// Skeleton placeholder — rendered for initial SSR, replaced on hydration");
            self.line("__html += '<div data-nectar-skeleton=\"true\" class=\"nectar-skeleton\">';");
            self.generate_template_ssr(&skel.body.body, comp_name, false);
            self.line("__html += '</div>';");
            self.line("// Nectar skeleton built-in pulse animation styles");
            self.line("__html += '<style>.nectar-skeleton{animation:nectar-skeleton-pulse 1.5s ease-in-out infinite}");
            self.line("@keyframes nectar-skeleton-pulse{0%{opacity:1}50%{opacity:0.4}100%{opacity:1}}</style>';");
        }

        self.generate_template_ssr(&comp.render.body, comp_name, true);

        self.line("return __html;");
        self.indent -= 1;
        self.line("}");
        self.line(&format!("module.exports.render_{} = render_{};", comp_name, comp_name));
        self.line("");
    }

    fn generate_template_ssr(
        &mut self,
        node: &TemplateNode,
        comp_name: &str,
        is_root: bool,
    ) {
        match node {
            TemplateNode::Element(el) => {
                let key = self.next_key();

                // Open tag
                let mut open_tag = format!("<{}", el.tag);

                // Add hydration marker on root element
                if is_root {
                    open_tag.push_str(&format!(
                        " data-nectar-hydrate=\"{}\"",
                        comp_name
                    ));
                }

                // Add hydration key for dynamic content mapping
                open_tag.push_str(&format!(" data-nectar-key=\"{}\"", key));

                self.line(&format!("__html += '{}';", self.escape_js_string(&open_tag)));

                // Static and dynamic attributes
                for attr in &el.attributes {
                    match attr {
                        Attribute::Static { name, value } => {
                            self.line(&format!(
                                "__html += ' {}=\"{}\"';",
                                self.escape_js_string(name),
                                self.escape_js_string(value),
                            ));
                        }
                        Attribute::Dynamic { name, value } => {
                            let val_js = self.expr_to_js(value);
                            self.line(&format!(
                                "__html += ' {}=\"' + __escapeHtml({}) + '\"';",
                                self.escape_js_string(name),
                                val_js,
                            ));
                        }
                        Attribute::EventHandler { .. } => {
                            // Event handlers are not rendered on the server;
                            // they get attached during hydration on the client.
                        }
                        Attribute::Aria { name, value } => {
                            let val_js = self.expr_to_js(value);
                            self.line(&format!(
                                "__html += ' {}=\"' + __escapeHtml({}) + '\"';",
                                self.escape_js_string(name),
                                val_js,
                            ));
                        }
                        Attribute::Role { value } => {
                            self.line(&format!(
                                "__html += ' role=\"{}\"';",
                                self.escape_js_string(value),
                            ));
                        }
                        Attribute::Bind { property, signal } => {
                            // For SSR, render the initial value from the signal
                            self.line(&format!(
                                "__html += ' {}=\"' + __escapeHtml({}) + '\"';",
                                self.escape_js_string(property),
                                signal,
                            ));
                        }
                    }
                }

                self.line("__html += '>';");

                // Void elements don't get closing tags
                let void_elements = [
                    "area", "base", "br", "col", "embed", "hr", "img",
                    "input", "link", "meta", "param", "source", "track", "wbr",
                ];
                if !void_elements.contains(&el.tag.as_str()) {
                    // Render children
                    for child in &el.children {
                        self.generate_template_ssr(child, comp_name, false);
                    }

                    // Close tag
                    self.line(&format!("__html += '</{}>'; ", el.tag));
                }
            }
            TemplateNode::TextLiteral(text) => {
                let escaped = self.escape_js_string(text);
                self.line(&format!("__html += '{}';", escaped));
            }
            TemplateNode::Expression(expr) => {
                let key = self.next_key();
                let js = self.expr_to_js(expr);
                self.line(&format!(
                    "__html += '<span data-nectar-key=\"{}\">' + __escapeHtml({}) + '</span>';",
                    key, js
                ));
            }
            TemplateNode::Link { to, children } => {
                let key = self.next_key();
                let href_js = self.expr_to_js(to);

                self.line(&format!(
                    "__html += '<a href=\"' + __escapeHtml({}) + '\" data-nectar-key=\"{}\">';",
                    href_js, key
                ));

                for child in children {
                    self.generate_template_ssr(child, comp_name, false);
                }

                self.line("__html += '</a>';");
            }
            TemplateNode::Fragment(children) => {
                for child in children {
                    self.generate_template_ssr(child, comp_name, false);
                }
            }
        }
    }

    fn generate_router(&mut self, router: &RouterDef) {
        let router_name = &router.name;
        self.line(&format!("// === Router: {} ===", router_name));
        self.line(&format!(
            "function render_{}(props) {{",
            router_name
        ));
        self.indent += 1;
        self.line("const url = props.__url || '/';");

        // Build route matching logic
        self.line("let __html = '';");
        for (i, route) in router.routes.iter().enumerate() {
            let condition = if route.params.is_empty() {
                format!("url === '{}'", route.path)
            } else {
                // Build a regex for parameterized routes
                let regex = self.route_path_to_regex(&route.path);
                format!("{}.test(url)", regex)
            };

            let keyword = if i == 0 { "if" } else { "else if" };
            self.line(&format!("{} ({}) {{", keyword, condition));
            self.indent += 1;

            // Check guard if present
            if let Some(ref guard) = route.guard {
                let guard_js = self.expr_to_js(guard);
                self.line(&format!("if ({}) {{", guard_js));
                self.indent += 1;
                self.line(&format!(
                    "__html = render_{}(props);",
                    route.component
                ));
                self.indent -= 1;
                self.line("}");
            } else {
                self.line(&format!(
                    "__html = render_{}(props);",
                    route.component
                ));
            }

            self.indent -= 1;
            self.line("}");
        }

        // Fallback
        if router.fallback.is_some() {
            self.line("else {");
            self.indent += 1;
            self.line("__html = '<div data-nectar-hydrate=\"__fallback\">Not Found</div>';");
            self.indent -= 1;
            self.line("}");
        }

        self.line("return __html;");
        self.indent -= 1;
        self.line("}");
        self.line(&format!(
            "module.exports.render_{} = render_{};",
            router_name, router_name
        ));
        self.line("");
    }

    // --- Helpers ---

    /// Convert a Nectar expression to a JavaScript expression string.
    /// This is a simplified conversion for evaluating initial values at SSR time.
    fn expr_to_js(&self, expr: &Expr) -> String {
        match expr {
            Expr::Integer(n) => n.to_string(),
            Expr::Float(f) => f.to_string(),
            Expr::StringLit(s) => format!("'{}'", self.escape_js_string(s)),
            Expr::Bool(b) => b.to_string(),
            Expr::Ident(name) => name.clone(),
            Expr::SelfExpr => "this".to_string(),
            Expr::Binary { op, left, right } => {
                let l = self.expr_to_js(left);
                let r = self.expr_to_js(right);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "===",
                    BinOp::Neq => "!==",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::Lte => "<=",
                    BinOp::Gte => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Unary { op, operand } => {
                let o = self.expr_to_js(operand);
                match op {
                    UnaryOp::Neg => format!("(-{})", o),
                    UnaryOp::Not => format!("(!{})", o),
                }
            }
            Expr::FieldAccess { object, field } => {
                let obj = self.expr_to_js(object);
                format!("{}.{}", obj, field)
            }
            Expr::MethodCall { object, method, args } => {
                let obj = self.expr_to_js(object);
                let args_js: Vec<String> = args.iter().map(|a| self.expr_to_js(a)).collect();
                format!("{}.{}({})", obj, method, args_js.join(", "))
            }
            Expr::FnCall { callee, args } => {
                let callee_js = self.expr_to_js(callee);
                let args_js: Vec<String> = args.iter().map(|a| self.expr_to_js(a)).collect();
                format!("{}({})", callee_js, args_js.join(", "))
            }
            Expr::Index { object, index } => {
                let obj = self.expr_to_js(object);
                let idx = self.expr_to_js(index);
                format!("{}[{}]", obj, idx)
            }
            Expr::If { condition, then_block, else_block } => {
                let cond = self.expr_to_js(condition);
                let then_js = if let Some(last) = then_block.stmts.last() {
                    self.stmt_to_js(last)
                } else {
                    "undefined".to_string()
                };
                let else_js = if let Some(eb) = else_block {
                    if let Some(last) = eb.stmts.last() {
                        self.stmt_to_js(last)
                    } else {
                        "undefined".to_string()
                    }
                } else {
                    "undefined".to_string()
                };
                format!("({} ? {} : {})", cond, then_js, else_js)
            }
            Expr::StructInit { name, fields } => {
                let fields_js: Vec<String> = fields
                    .iter()
                    .map(|(k, v)| format!("{}: {}", k, self.expr_to_js(v)))
                    .collect();
                format!("/* {} */ {{ {} }}", name, fields_js.join(", "))
            }
            Expr::Closure { params, body } => {
                let params_js: Vec<String> = params.iter().map(|(n, _)| n.clone()).collect();
                let body_js = self.expr_to_js(body);
                format!("({}) => {}", params_js.join(", "), body_js)
            }
            _ => "undefined /* unsupported SSR expr */".to_string(),
        }
    }

    fn stmt_to_js(&self, stmt: &Stmt) -> String {
        match stmt {
            Stmt::Expr(expr) => self.expr_to_js(expr),
            Stmt::Return(Some(expr)) => self.expr_to_js(expr),
            _ => "undefined".to_string(),
        }
    }

    fn route_path_to_regex(&self, path: &str) -> String {
        let mut regex = String::from("/^");
        for segment in path.split('/') {
            if segment.is_empty() {
                continue;
            }
            regex.push_str("\\/");
            if segment.starts_with(':') {
                regex.push_str("[^/]+");
            } else if segment == "*" {
                regex.push_str(".*");
            } else {
                regex.push_str(segment);
            }
        }
        regex.push_str("$/");
        regex
    }

    fn escape_js_string(&self, s: &str) -> String {
        s.replace('\\', "\\\\")
            .replace('\'', "\\'")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
    }

    fn next_key(&mut self) -> u32 {
        let k = self.key_counter;
        self.key_counter += 1;
        k
    }

    fn emit(&mut self, s: &str) {
        let indent = "  ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn line(&mut self, s: &str) {
        self.emit(s);
    }
}
