//! Generated by Nectar compiler — do not edit.
//! Source: .nectar → Rust → cargo build → WASM

// Fast WASM allocator — replaces dlmalloc for better allocation performance
#[global_allocator]
static ALLOCATOR: lol_alloc::AssumeSingleThreaded<lol_alloc::FreeListAllocator> =
    unsafe { lol_alloc::AssumeSingleThreaded::new(lol_alloc::FreeListAllocator::new()) };

#[allow(unused_imports)]
use honeycomb::element::ElementTree;
use honeycomb::layout;
use honeycomb::measure::EstimateMeasurer;
use honeycomb::canvas_syscalls::*;
use std::cell::RefCell;
use serde::Deserialize;

/// Scratch buffer for fetch responses, storage reads, hash reads
const SCRATCH_SIZE: usize = 4 * 1024 * 1024; // 4MB — handles 10K+ product API responses
static mut SCRATCH: [u8; SCRATCH_SIZE] = [0u8; SCRATCH_SIZE];

/// Helper: read a string from WASM memory via syscall that writes into a buffer
fn read_storage(key: &str) -> String {
    unsafe {
        let len = storage_get(key.as_ptr(), key.len() as u32, SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        if len == 0 { return String::new(); }
        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()
    }
}

fn write_storage(key: &str, val: &str) {
    unsafe { storage_set(key.as_ptr(), key.len() as u32, val.as_ptr(), val.len() as u32); }
}

fn remove_storage(key: &str) {
    unsafe { storage_remove(key.as_ptr(), key.len() as u32); }
}

fn get_hash() -> String {
    unsafe {
        let len = get_location_hash(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        if len == 0 { return String::new(); }
        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()
    }
}

fn set_hash(hash: &str) {
    unsafe { set_location_hash(hash.as_ptr(), hash.len() as u32); }
}

fn fetch_get(url: &str, cb_idx: u32) {
    unsafe { fetch_request(url.as_ptr(), url.len() as u32, 0, std::ptr::null(), 0, cb_idx); }
}

fn fetch_post(url: &str, body: &[u8], cb_idx: u32) {
    unsafe {
        fetch_set_header("Content-Type".as_ptr(), 12, "application/json".as_ptr(), 16);
        fetch_request(url.as_ptr(), url.len() as u32, 1, body.as_ptr(), body.len() as u32, cb_idx);
    }
}

fn read_response() -> (i32, Vec<u8>) {
    unsafe {
        let status = fetch_response_status();
        let len = fetch_response_body(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        (status, SCRATCH[..len as usize].to_vec())
    }
}

fn set_auth_header(token: &str) {
    let val = format!("Bearer {}", token);
    unsafe { fetch_set_header("Authorization".as_ptr(), 13, val.as_ptr(), val.len() as u32); }
}

fn with_tree<R>(f: impl FnOnce(&mut ElementTree) -> R) -> R {
    honeycomb::wasm_api::TREE.with(|t| f(&mut t.borrow_mut()))
}

fn perf_now() -> f64 { unsafe { performance_now() } }
static mut INIT_START: f64 = 0.0;

fn update_metric_text(name: &str, value: &str) {
    honeycomb::canvas_app::METRIC_TEXT_IDS.with(|m| {
        let ids: Vec<(String, u32)> = m.borrow().clone();
        // Try wasm_api::TREE first (handler may have just rebuilt here)
        honeycomb::wasm_api::TREE.with(|t| {
            let mut tree = t.borrow_mut();
            for (n, id) in &ids {
                if n == name {
                    if let Some(el) = tree.get_mut(*id) { el.text = Some(value.to_string()); }
                }
            }
        });
        // Also try AppState.tree (for filter/sort that don't rebuild)
        honeycomb::canvas_app::STATE.with(|s| {
            if let Some(ref mut app) = *s.borrow_mut() {
                for (n, id) in &ids {
                    if n == name {
                        if let Some(el) = app.tree.get_mut(*id) { el.text = Some(value.to_string()); }
                    }
                }
            }
        });
    });
}

fn filter_by(attr: &str, value: &str) {
    honeycomb::canvas_app::wasm_filter_by_attr(
        attr.as_ptr(), attr.len() as u32, value.as_ptr(), value.len() as u32);
}
fn to_ms_string(start: f64, end: f64) -> String {
    let elapsed = ((end - start) * 100.0) as i32;
    let d = elapsed / 100;
    let c = elapsed - d * 100;
    if c < 10 { format!("{}ms", d) } else { format!("{}.{}ms", d, c) }
}

// ── Render: layout only (painting done by Honeycomb's app_render) ──

fn render() {
    honeycomb::wasm_api::TREE.with(|t| {
        let mut tree = t.borrow_mut();
        let mut measurer = EstimateMeasurer;
        let vw = unsafe { canvas_get_width() };
        let vh = unsafe { canvas_get_height() };
        layout::compute(&mut tree, vw, 999999.0, &mut measurer);
    });
}

#[no_mangle]
pub extern "C" fn nectar_init(_vw: f32, _vh: f32) {
    let _init_t0 = perf_now();
    unsafe { INIT_START = _init_t0; }
    app_mount();
    let _init_elapsed = to_ms_string(_init_t0, perf_now());
    APP_STATE.with(|s| s.borrow_mut().total_ms = _init_elapsed.clone());
    update_metric_text("total_ms", &_init_elapsed);
    let _heap = APP_STATE.with(|s| s.borrow().heap_ms.clone());
    update_metric_text("heap_ms", &_heap);
}

