//! Generated by Nectar compiler — do not edit.
//! Source: .nectar → Rust → cargo build → WASM

// Fast WASM allocator — replaces dlmalloc for better allocation performance
#[global_allocator]
static ALLOCATOR: lol_alloc::AssumeSingleThreaded<lol_alloc::FreeListAllocator> =
    unsafe { lol_alloc::AssumeSingleThreaded::new(lol_alloc::FreeListAllocator::new()) };

#[allow(unused_imports)]
use honeycomb::element::ElementTree;
use honeycomb::layout;
use honeycomb::measure::EstimateMeasurer;
use honeycomb::canvas_syscalls::*;
use std::cell::RefCell;
use serde::Deserialize;

/// Scratch buffer for fetch responses, storage reads, hash reads
const SCRATCH_SIZE: usize = 4 * 1024 * 1024; // 4MB — handles 10K+ product API responses
static mut SCRATCH: [u8; SCRATCH_SIZE] = [0u8; SCRATCH_SIZE];

/// Helper: read a string from WASM memory via syscall that writes into a buffer
fn read_storage(key: &str) -> String {
    unsafe {
        let len = storage_get(key.as_ptr(), key.len() as u32, SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        if len == 0 { return String::new(); }
        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()
    }
}

fn write_storage(key: &str, val: &str) {
    unsafe { storage_set(key.as_ptr(), key.len() as u32, val.as_ptr(), val.len() as u32); }
}

fn remove_storage(key: &str) {
    unsafe { storage_remove(key.as_ptr(), key.len() as u32); }
}

fn get_hash() -> String {
    unsafe {
        let len = get_location_hash(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        if len == 0 { return String::new(); }
        String::from_utf8_lossy(&SCRATCH[..len as usize]).to_string()
    }
}

fn set_hash(hash: &str) {
    unsafe { set_location_hash(hash.as_ptr(), hash.len() as u32); }
}

fn fetch_get(url: &str, cb_idx: u32) {
    unsafe { fetch_request(url.as_ptr(), url.len() as u32, 0, std::ptr::null(), 0, cb_idx); }
}

fn fetch_post(url: &str, body: &[u8], cb_idx: u32) {
    unsafe {
        fetch_set_header("Content-Type".as_ptr(), 12, "application/json".as_ptr(), 16);
        fetch_request(url.as_ptr(), url.len() as u32, 1, body.as_ptr(), body.len() as u32, cb_idx);
    }
}

fn read_response() -> (i32, Vec<u8>) {
    unsafe {
        let status = fetch_response_status();
        let len = fetch_response_body(SCRATCH.as_mut_ptr(), SCRATCH_SIZE as u32);
        (status, SCRATCH[..len as usize].to_vec())
    }
}

fn set_auth_header(token: &str) {
    let val = format!("Bearer {}", token);
    unsafe { fetch_set_header("Authorization".as_ptr(), 13, val.as_ptr(), val.len() as u32); }
}

fn with_tree<R>(f: impl FnOnce(&mut ElementTree) -> R) -> R {
    honeycomb::wasm_api::TREE.with(|t| f(&mut t.borrow_mut()))
}

fn perf_now() -> f64 { unsafe { performance_now() } }
static mut INIT_START: f64 = 0.0;

fn update_metric_text(name: &str, value: &str) {
    honeycomb::canvas_app::METRIC_TEXT_IDS.with(|m| {
        let ids: Vec<(String, u32)> = m.borrow().clone();
        // Try wasm_api::TREE first (handler may have just rebuilt here)
        honeycomb::wasm_api::TREE.with(|t| {
            let mut tree = t.borrow_mut();
            for (n, id) in &ids {
                if n == name {
                    if let Some(el) = tree.get_mut(*id) { el.text = Some(value.to_string()); }
                }
            }
        });
        // Also try AppState.tree (for filter/sort that don't rebuild)
        honeycomb::canvas_app::STATE.with(|s| {
            if let Some(ref mut app) = *s.borrow_mut() {
                for (n, id) in &ids {
                    if n == name {
                        if let Some(el) = app.tree.get_mut(*id) { el.text = Some(value.to_string()); }
                    }
                }
            }
        });
    });
}

fn filter_by(attr: &str, value: &str) {
    honeycomb::canvas_app::wasm_filter_by_attr(
        attr.as_ptr(), attr.len() as u32, value.as_ptr(), value.len() as u32);
}
fn to_ms_string(start: f64, end: f64) -> String {
    let us = ((end - start) * 1000.0) as u64;
    if us >= 1000 { format!("{}.{:02}ms", us / 1000, (us % 1000) / 10) }
    else { format!("0.{:03}ms", us) }
}

#[derive(Clone, Default, Deserialize)]
struct Product {
    id: i32,
    #[serde(borrow)]
    name: &'static str,
    #[serde(borrow)]
    category: &'static str,
    price_cents: i32,
    #[serde(borrow)]
    stock_status: &'static str,
    #[serde(borrow)]
    image_url: &'static str,
}

struct EcommercePanelState {
    products: Vec<Product>,
    product_count: i32,
    cart_count: i32,
    cart_open: i32,
    active_cat: String,
    sort_mode: String,
    status: String,
    heap_ms: String,
    total_ms: String,
    last_op_ms: String,
    _element_ids: Vec<u32>,
    _card_cats: Vec<(u32, String)>,
}

thread_local! {
    static ECOMMERCEPANEL_STATE: RefCell<EcommercePanelState> = RefCell::new(EcommercePanelState {
        products: vec![],
        product_count: 0,
        cart_count: 0,
        cart_open: 0,
        active_cat: "All".to_string(),
        sort_mode: "Default".to_string(),
        status: "Loading...".to_string(),
        heap_ms: "—".to_string(),
        total_ms: "—".to_string(),
        last_op_ms: "—".to_string(),
        _element_ids: Vec::new(),
        _card_cats: Vec::new(),
    });
}

fn ecommercepanel_mount() {
    ECOMMERCEPANEL_STATE.with(|_state_cell| {
        let _state_ref = _state_cell.borrow();
        let products = &_state_ref.products;
        let product_count = _state_ref.product_count;
        let cart_count = _state_ref.cart_count;
        let cart_open = _state_ref.cart_open;
        let active_cat = _state_ref.active_cat.clone();
        let sort_mode = _state_ref.sort_mode.clone();
        let status = _state_ref.status.clone();
        let heap_ms = _state_ref.heap_ms.clone();
        let total_ms = _state_ref.total_ms.clone();
        let last_op_ms = _state_ref.last_op_ms.clone();
        with_tree(|tree| {
            let root = tree.root_id();
            let el_0 = tree.create("div");
            tree.append_child(root, el_0);
            tree.set_style(el_0, "direction", "vertical");
            tree.set_style(el_0, "width", "fill");
            tree.set_style(el_0, "height", "hug");
            tree.set_style(el_0, "background-color", "#09090b");
            tree.set_style(el_0, "gap", "0");
            tree.set_style(el_0, "align", "center");
            let el_1 = tree.create("div");
            tree.append_child(el_0, el_1);
            tree.set_style(el_1, "direction", "horizontal");
            tree.set_style(el_1, "width", "fill");
            tree.set_style(el_1, "height", "36px");
            tree.set_style(el_1, "background-color", "#1a1400");
            tree.set_style(el_1, "align", "center");
            tree.set_style(el_1, "justify", "center");
            tree.set_style(el_1, "gap", "8");
            let el_2 = tree.create("div");
            tree.append_child(el_1, el_2);
            tree.set_style(el_2, "font-size", "13px");
            tree.set_style(el_2, "font-weight", "500");
            tree.set_style(el_2, "color", "#ffa11e");
            tree.set_style(el_2, "width", "hug");
            tree.set_style(el_2, "height", "hug");
            if let Some(el) = tree.get_mut(el_2) { el.text = Some("Free shipping on orders over $50 · Spring Sale: 20% off select items".into()); }
            let el_3 = tree.create("div");
            tree.append_child(el_0, el_3);
            tree.set_style(el_3, "direction", "horizontal");
            tree.set_style(el_3, "width", "fill");
            tree.set_style(el_3, "height", "56px");
            tree.set_style(el_3, "background-color", "#09090b");
            tree.set_style(el_3, "border-color", "#27272a");
            tree.set_style(el_3, "border-width", "0");
            tree.set_style(el_3, "padding-left", "32");
            tree.set_style(el_3, "padding-right", "32");
            tree.set_style(el_3, "gap", "24");
            tree.set_style(el_3, "align", "center");
            let el_4 = tree.create("div");
            tree.append_child(el_3, el_4);
            tree.set_style(el_4, "font-size", "20px");
            tree.set_style(el_4, "font-weight", "800");
            tree.set_style(el_4, "color", "#ffa11e");
            tree.set_style(el_4, "width", "hug");
            tree.set_style(el_4, "height", "hug");
            if let Some(el) = tree.get_mut(el_4) { el.text = Some("nectar".into()); }
            let el_5 = tree.create("div");
            tree.append_child(el_3, el_5);
            tree.set_style(el_5, "width", "1px");
            tree.set_style(el_5, "height", "20px");
            tree.set_style(el_5, "background-color", "#27272a");
            let el_6 = tree.create("div");
            tree.append_child(el_3, el_6);
            tree.set_style(el_6, "font-size", "14px");
            tree.set_style(el_6, "color", "#a1a1aa");
            tree.set_style(el_6, "width", "hug");
            tree.set_style(el_6, "height", "hug");
            if let Some(el) = tree.get_mut(el_6) { el.text = Some("Shop".into()); }
            let el_7 = tree.create("div");
            tree.append_child(el_3, el_7);
            tree.set_style(el_7, "font-size", "14px");
            tree.set_style(el_7, "color", "#a1a1aa");
            tree.set_style(el_7, "width", "hug");
            tree.set_style(el_7, "height", "hug");
            if let Some(el) = tree.get_mut(el_7) { el.text = Some("Categories".into()); }
            let el_8 = tree.create("div");
            tree.append_child(el_3, el_8);
            tree.set_style(el_8, "font-size", "14px");
            tree.set_style(el_8, "color", "#a1a1aa");
            tree.set_style(el_8, "width", "hug");
            tree.set_style(el_8, "height", "hug");
            if let Some(el) = tree.get_mut(el_8) { el.text = Some("About".into()); }
            let el_9 = tree.create("div");
            tree.append_child(el_3, el_9);
            tree.set_style(el_9, "width", "fill");
            tree.set_style(el_9, "height", "hug");
            let el_10 = tree.create("div");
            tree.append_child(el_3, el_10);
            tree.set_style(el_10, "font-size", "14px");
            tree.set_style(el_10, "font-weight", "600");
            tree.set_style(el_10, "color", "#000");
            tree.set_style(el_10, "background-color", "#ffa11e");
            tree.set_style(el_10, "padding", "10");
            tree.set_style(el_10, "padding-left", "20");
            tree.set_style(el_10, "padding-right", "20");
            tree.set_style(el_10, "border-radius", "8");
            tree.set_style(el_10, "width", "hug");
            tree.set_style(el_10, "height", "hug");
            // on:click -> toggle_cart (cb_idx=2)
            tree.add_event(el_10, "click", 2);
            if let Some(el) = tree.get_mut(el_10) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_10) { el.text = Some(format!("Cart ({})", cart_count).to_string()); }
            honeycomb::canvas_app::register_text_binding(el_10, "cart_count".as_ptr(), 10, "Cart ({})".as_ptr(), 9);
            let el_11 = tree.create("div");
            tree.append_child(el_0, el_11);
            tree.set_style(el_11, "width", "fill");
            tree.set_style(el_11, "height", "1px");
            tree.set_style(el_11, "background-color", "#27272a");
            let el_12 = tree.create("div");
            tree.append_child(el_0, el_12);
            tree.set_style(el_12, "direction", "layer");
            tree.set_style(el_12, "width", "fill");
            tree.set_style(el_12, "height", "hug");
            let el_13 = tree.create("div");
            tree.append_child(el_12, el_13);
            tree.set_style(el_13, "direction", "vertical");
            tree.set_style(el_13, "width", "fill");
            tree.set_style(el_13, "max-width", "1280px");
            tree.set_style(el_13, "height", "hug");
            tree.set_style(el_13, "padding", "32");
            tree.set_style(el_13, "padding-top", "24");
            tree.set_style(el_13, "gap", "24");
            let el_14 = tree.create("div");
            tree.append_child(el_13, el_14);
            tree.set_style(el_14, "direction", "horizontal");
            tree.set_style(el_14, "gap", "12");
            tree.set_style(el_14, "wrap", "true");
            tree.set_style(el_14, "width", "fill");
            tree.set_style(el_14, "height", "hug");
            let el_15 = tree.create("div");
            tree.append_child(el_14, el_15);
            tree.set_style(el_15, "direction", "vertical");
            tree.set_style(el_15, "width", "180px");
            tree.set_style(el_15, "height", "hug");
            tree.set_style(el_15, "background-color", "#18181b");
            tree.set_style(el_15, "border-color", "#27272a");
            tree.set_style(el_15, "border-width", "1");
            tree.set_style(el_15, "border-radius", "10");
            tree.set_style(el_15, "padding", "12");
            tree.set_style(el_15, "gap", "2");
            let el_16 = tree.create("div");
            tree.append_child(el_15, el_16);
            tree.set_style(el_16, "font-size", "10px");
            tree.set_style(el_16, "font-weight", "600");
            tree.set_style(el_16, "color", "#52525b");
            tree.set_style(el_16, "width", "hug");
            tree.set_style(el_16, "height", "hug");
            if let Some(el) = tree.get_mut(el_16) { el.text = Some("HEAP INIT".into()); }
            let el_17 = tree.create("div");
            tree.append_child(el_15, el_17);
            tree.set_style(el_17, "font-size", "22px");
            tree.set_style(el_17, "font-weight", "800");
            tree.set_style(el_17, "color", "#10b981");
            tree.set_style(el_17, "width", "hug");
            tree.set_style(el_17, "height", "hug");
            if let Some(el) = tree.get_mut(el_17) { el.text = Some(heap_ms.to_string()); }
            honeycomb::canvas_app::register_metric_text("heap_ms".as_ptr(), 7, el_17);
            honeycomb::canvas_app::register_text_binding(el_17, "heap_ms".as_ptr(), 7, "{}".as_ptr(), 2);
            let el_18 = tree.create("div");
            tree.append_child(el_14, el_18);
            tree.set_style(el_18, "direction", "vertical");
            tree.set_style(el_18, "width", "180px");
            tree.set_style(el_18, "height", "hug");
            tree.set_style(el_18, "background-color", "#18181b");
            tree.set_style(el_18, "border-color", "#27272a");
            tree.set_style(el_18, "border-width", "1");
            tree.set_style(el_18, "border-radius", "10");
            tree.set_style(el_18, "padding", "12");
            tree.set_style(el_18, "gap", "2");
            let el_19 = tree.create("div");
            tree.append_child(el_18, el_19);
            tree.set_style(el_19, "font-size", "10px");
            tree.set_style(el_19, "font-weight", "600");
            tree.set_style(el_19, "color", "#52525b");
            tree.set_style(el_19, "width", "hug");
            tree.set_style(el_19, "height", "hug");
            if let Some(el) = tree.get_mut(el_19) { el.text = Some("TOTAL INIT".into()); }
            let el_20 = tree.create("div");
            tree.append_child(el_18, el_20);
            tree.set_style(el_20, "font-size", "22px");
            tree.set_style(el_20, "font-weight", "800");
            tree.set_style(el_20, "color", "#58a6ff");
            tree.set_style(el_20, "width", "hug");
            tree.set_style(el_20, "height", "hug");
            if let Some(el) = tree.get_mut(el_20) { el.text = Some(total_ms.to_string()); }
            honeycomb::canvas_app::register_metric_text("total_ms".as_ptr(), 8, el_20);
            honeycomb::canvas_app::register_text_binding(el_20, "total_ms".as_ptr(), 8, "{}".as_ptr(), 2);
            let el_21 = tree.create("div");
            tree.append_child(el_14, el_21);
            tree.set_style(el_21, "direction", "vertical");
            tree.set_style(el_21, "width", "180px");
            tree.set_style(el_21, "height", "hug");
            tree.set_style(el_21, "background-color", "#18181b");
            tree.set_style(el_21, "border-color", "#27272a");
            tree.set_style(el_21, "border-width", "1");
            tree.set_style(el_21, "border-radius", "10");
            tree.set_style(el_21, "padding", "12");
            tree.set_style(el_21, "gap", "2");
            let el_22 = tree.create("div");
            tree.append_child(el_21, el_22);
            tree.set_style(el_22, "font-size", "10px");
            tree.set_style(el_22, "font-weight", "600");
            tree.set_style(el_22, "color", "#52525b");
            tree.set_style(el_22, "width", "hug");
            tree.set_style(el_22, "height", "hug");
            if let Some(el) = tree.get_mut(el_22) { el.text = Some("PRODUCTS".into()); }
            let el_23 = tree.create("div");
            tree.append_child(el_21, el_23);
            tree.set_style(el_23, "font-size", "22px");
            tree.set_style(el_23, "font-weight", "800");
            tree.set_style(el_23, "color", "#58a6ff");
            tree.set_style(el_23, "width", "hug");
            tree.set_style(el_23, "height", "hug");
            if let Some(el) = tree.get_mut(el_23) { el.text = Some(format!("{}", product_count).to_string()); }
            honeycomb::canvas_app::register_metric_text("product_count".as_ptr(), 13, el_23);
            honeycomb::canvas_app::register_text_binding(el_23, "product_count".as_ptr(), 13, "{}".as_ptr(), 2);
            let el_24 = tree.create("div");
            tree.append_child(el_14, el_24);
            tree.set_style(el_24, "direction", "vertical");
            tree.set_style(el_24, "width", "180px");
            tree.set_style(el_24, "height", "hug");
            tree.set_style(el_24, "background-color", "#18181b");
            tree.set_style(el_24, "border-color", "#27272a");
            tree.set_style(el_24, "border-width", "1");
            tree.set_style(el_24, "border-radius", "10");
            tree.set_style(el_24, "padding", "12");
            tree.set_style(el_24, "gap", "2");
            let el_25 = tree.create("div");
            tree.append_child(el_24, el_25);
            tree.set_style(el_25, "font-size", "10px");
            tree.set_style(el_25, "font-weight", "600");
            tree.set_style(el_25, "color", "#52525b");
            tree.set_style(el_25, "width", "hug");
            tree.set_style(el_25, "height", "hug");
            if let Some(el) = tree.get_mut(el_25) { el.text = Some("CART".into()); }
            let el_26 = tree.create("div");
            tree.append_child(el_24, el_26);
            tree.set_style(el_26, "font-size", "22px");
            tree.set_style(el_26, "font-weight", "800");
            tree.set_style(el_26, "color", "#ffa11e");
            tree.set_style(el_26, "width", "hug");
            tree.set_style(el_26, "height", "hug");
            if let Some(el) = tree.get_mut(el_26) { el.text = Some(format!("{}", cart_count).to_string()); }
            honeycomb::canvas_app::register_metric_text("cart_count".as_ptr(), 10, el_26);
            honeycomb::canvas_app::register_text_binding(el_26, "cart_count".as_ptr(), 10, "{}".as_ptr(), 2);
            let el_27 = tree.create("div");
            tree.append_child(el_14, el_27);
            tree.set_style(el_27, "direction", "vertical");
            tree.set_style(el_27, "width", "180px");
            tree.set_style(el_27, "height", "hug");
            tree.set_style(el_27, "background-color", "#18181b");
            tree.set_style(el_27, "border-color", "#27272a");
            tree.set_style(el_27, "border-width", "1");
            tree.set_style(el_27, "border-radius", "10");
            tree.set_style(el_27, "padding", "12");
            tree.set_style(el_27, "gap", "2");
            let el_28 = tree.create("div");
            tree.append_child(el_27, el_28);
            tree.set_style(el_28, "font-size", "10px");
            tree.set_style(el_28, "font-weight", "600");
            tree.set_style(el_28, "color", "#52525b");
            tree.set_style(el_28, "width", "hug");
            tree.set_style(el_28, "height", "hug");
            if let Some(el) = tree.get_mut(el_28) { el.text = Some("LAST OP".into()); }
            let el_29 = tree.create("div");
            tree.append_child(el_27, el_29);
            tree.set_style(el_29, "font-size", "22px");
            tree.set_style(el_29, "font-weight", "800");
            tree.set_style(el_29, "color", "#bc8cff");
            tree.set_style(el_29, "width", "hug");
            tree.set_style(el_29, "height", "hug");
            if let Some(el) = tree.get_mut(el_29) { el.text = Some(last_op_ms.to_string()); }
            honeycomb::canvas_app::register_metric_text("last_op_ms".as_ptr(), 10, el_29);
            honeycomb::canvas_app::register_text_binding(el_29, "last_op_ms".as_ptr(), 10, "{}".as_ptr(), 2);
            let el_30 = tree.create("div");
            tree.append_child(el_14, el_30);
            tree.set_style(el_30, "direction", "vertical");
            tree.set_style(el_30, "width", "180px");
            tree.set_style(el_30, "height", "hug");
            tree.set_style(el_30, "background-color", "#18181b");
            tree.set_style(el_30, "border-color", "#27272a");
            tree.set_style(el_30, "border-width", "1");
            tree.set_style(el_30, "border-radius", "10");
            tree.set_style(el_30, "padding", "12");
            tree.set_style(el_30, "gap", "2");
            let el_31 = tree.create("div");
            tree.append_child(el_30, el_31);
            tree.set_style(el_31, "font-size", "10px");
            tree.set_style(el_31, "font-weight", "600");
            tree.set_style(el_31, "color", "#52525b");
            tree.set_style(el_31, "width", "hug");
            tree.set_style(el_31, "height", "hug");
            if let Some(el) = tree.get_mut(el_31) { el.text = Some("FILTER".into()); }
            let el_32 = tree.create("div");
            tree.append_child(el_30, el_32);
            tree.set_style(el_32, "font-size", "22px");
            tree.set_style(el_32, "font-weight", "800");
            tree.set_style(el_32, "color", "#10b981");
            tree.set_style(el_32, "width", "hug");
            tree.set_style(el_32, "height", "hug");
            if let Some(el) = tree.get_mut(el_32) { el.text = Some(active_cat.to_string()); }
            honeycomb::canvas_app::register_metric_text("active_cat".as_ptr(), 10, el_32);
            honeycomb::canvas_app::register_text_binding(el_32, "active_cat".as_ptr(), 10, "{}".as_ptr(), 2);
            let el_33 = tree.create("div");
            tree.append_child(el_13, el_33);
            tree.set_style(el_33, "direction", "horizontal");
            tree.set_style(el_33, "gap", "6");
            tree.set_style(el_33, "width", "fill");
            tree.set_style(el_33, "height", "hug");
            tree.set_style(el_33, "align", "center");
            let el_34 = tree.create("div");
            tree.append_child(el_33, el_34);
            tree.set_style(el_34, "font-size", "13px");
            tree.set_style(el_34, "color", "#71717a");
            tree.set_style(el_34, "width", "hug");
            tree.set_style(el_34, "height", "hug");
            if let Some(el) = tree.get_mut(el_34) { el.text = Some("Home".into()); }
            let el_35 = tree.create("div");
            tree.append_child(el_33, el_35);
            tree.set_style(el_35, "font-size", "13px");
            tree.set_style(el_35, "color", "#52525b");
            tree.set_style(el_35, "width", "hug");
            tree.set_style(el_35, "height", "hug");
            if let Some(el) = tree.get_mut(el_35) { el.text = Some("/".into()); }
            let el_36 = tree.create("div");
            tree.append_child(el_33, el_36);
            tree.set_style(el_36, "font-size", "13px");
            tree.set_style(el_36, "color", "#71717a");
            tree.set_style(el_36, "width", "hug");
            tree.set_style(el_36, "height", "hug");
            if let Some(el) = tree.get_mut(el_36) { el.text = Some("Shop".into()); }
            let el_37 = tree.create("div");
            tree.append_child(el_33, el_37);
            tree.set_style(el_37, "font-size", "13px");
            tree.set_style(el_37, "color", "#52525b");
            tree.set_style(el_37, "width", "hug");
            tree.set_style(el_37, "height", "hug");
            if let Some(el) = tree.get_mut(el_37) { el.text = Some("/".into()); }
            let el_38 = tree.create("div");
            tree.append_child(el_33, el_38);
            tree.set_style(el_38, "font-size", "13px");
            tree.set_style(el_38, "color", "#a1a1aa");
            tree.set_style(el_38, "width", "hug");
            tree.set_style(el_38, "height", "hug");
            if let Some(el) = tree.get_mut(el_38) { el.text = Some(active_cat.to_string()); }
            honeycomb::canvas_app::register_metric_text("active_cat".as_ptr(), 10, el_38);
            honeycomb::canvas_app::register_text_binding(el_38, "active_cat".as_ptr(), 10, "{}".as_ptr(), 2);
            let el_39 = tree.create("div");
            tree.append_child(el_13, el_39);
            tree.set_style(el_39, "direction", "horizontal");
            tree.set_style(el_39, "gap", "16");
            tree.set_style(el_39, "width", "fill");
            tree.set_style(el_39, "height", "hug");
            tree.set_style(el_39, "align", "center");
            let el_40 = tree.create("div");
            tree.append_child(el_39, el_40);
            tree.set_style(el_40, "direction", "vertical");
            tree.set_style(el_40, "gap", "4");
            tree.set_style(el_40, "width", "fill");
            tree.set_style(el_40, "height", "hug");
            let el_41 = tree.create("div");
            tree.append_child(el_40, el_41);
            tree.set_style(el_41, "font-size", "32px");
            tree.set_style(el_41, "font-weight", "800");
            tree.set_style(el_41, "color", "#fafafa");
            tree.set_style(el_41, "width", "hug");
            tree.set_style(el_41, "height", "hug");
            if let Some(el) = tree.get_mut(el_41) { el.text = Some("Shop All Products".into()); }
            let el_42 = tree.create("div");
            tree.append_child(el_40, el_42);
            tree.set_style(el_42, "font-size", "14px");
            tree.set_style(el_42, "color", "#71717a");
            tree.set_style(el_42, "width", "hug");
            tree.set_style(el_42, "height", "hug");
            if let Some(el) = tree.get_mut(el_42) { el.text = Some(format!("{} items · Built entirely in WASM", product_count).to_string()); }
            honeycomb::canvas_app::register_text_binding(el_42, "product_count".as_ptr(), 13, "{} items · Built entirely in WASM".as_ptr(), 34);
            let el_43 = tree.create("div");
            tree.append_child(el_13, el_43);
            tree.set_style(el_43, "font-size", "14px");
            tree.set_style(el_43, "color", "#52525b");
            tree.set_style(el_43, "background-color", "#18181b");
            tree.set_style(el_43, "border-color", "#27272a");
            tree.set_style(el_43, "border-width", "1");
            tree.set_style(el_43, "padding", "14");
            tree.set_style(el_43, "border-radius", "10");
            tree.set_style(el_43, "width", "fill");
            tree.set_style(el_43, "height", "hug");
            if let Some(el) = tree.get_mut(el_43) { el.text = Some("Search products...".into()); }
            let el_44 = tree.create("div");
            tree.append_child(el_13, el_44);
            tree.set_style(el_44, "direction", "horizontal");
            tree.set_style(el_44, "gap", "16");
            tree.set_style(el_44, "width", "fill");
            tree.set_style(el_44, "height", "hug");
            tree.set_style(el_44, "align", "center");
            tree.set_style(el_44, "wrap", "true");
            let el_45 = tree.create("div");
            tree.append_child(el_44, el_45);
            tree.set_style(el_45, "direction", "horizontal");
            tree.set_style(el_45, "gap", "8");
            tree.set_style(el_45, "height", "hug");
            tree.set_style(el_45, "width", "hug");
            let el_46 = tree.create("div");
            tree.append_child(el_45, el_46);
            honeycomb::canvas_app::register_pill("All".as_ptr(), 3, el_46);
            tree.set_style(el_46, "font-size", "13px");
            tree.set_style(el_46, "font-weight", "500");
            tree.set_style(el_46, "color", "#000");
            tree.set_style(el_46, "background-color", "#ffa11e");
            tree.set_style(el_46, "padding", "8");
            tree.set_style(el_46, "padding-left", "16");
            tree.set_style(el_46, "padding-right", "16");
            tree.set_style(el_46, "border-radius", "20");
            tree.set_style(el_46, "width", "hug");
            tree.set_style(el_46, "height", "hug");
            // on:click -> cat_all (cb_idx=5)
            tree.add_event(el_46, "click", 5);
            if let Some(el) = tree.get_mut(el_46) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_46) { el.text = Some("All".into()); }
            let el_47 = tree.create("div");
            tree.append_child(el_45, el_47);
            honeycomb::canvas_app::register_pill("Electronics".as_ptr(), 11, el_47);
            tree.set_style(el_47, "font-size", "13px");
            tree.set_style(el_47, "font-weight", "500");
            tree.set_style(el_47, "color", "#a1a1aa");
            tree.set_style(el_47, "background-color", "#18181b");
            tree.set_style(el_47, "padding", "8");
            tree.set_style(el_47, "padding-left", "16");
            tree.set_style(el_47, "padding-right", "16");
            tree.set_style(el_47, "border-radius", "20");
            tree.set_style(el_47, "width", "hug");
            tree.set_style(el_47, "height", "hug");
            // on:click -> cat_electronics (cb_idx=6)
            tree.add_event(el_47, "click", 6);
            if let Some(el) = tree.get_mut(el_47) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_47) { el.text = Some("Electronics".into()); }
            let el_48 = tree.create("div");
            tree.append_child(el_45, el_48);
            honeycomb::canvas_app::register_pill("Clothing".as_ptr(), 8, el_48);
            tree.set_style(el_48, "font-size", "13px");
            tree.set_style(el_48, "font-weight", "500");
            tree.set_style(el_48, "color", "#a1a1aa");
            tree.set_style(el_48, "background-color", "#18181b");
            tree.set_style(el_48, "padding", "8");
            tree.set_style(el_48, "padding-left", "16");
            tree.set_style(el_48, "padding-right", "16");
            tree.set_style(el_48, "border-radius", "20");
            tree.set_style(el_48, "width", "hug");
            tree.set_style(el_48, "height", "hug");
            // on:click -> cat_clothing (cb_idx=7)
            tree.add_event(el_48, "click", 7);
            if let Some(el) = tree.get_mut(el_48) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_48) { el.text = Some("Clothing".into()); }
            let el_49 = tree.create("div");
            tree.append_child(el_45, el_49);
            honeycomb::canvas_app::register_pill("Home Goods".as_ptr(), 10, el_49);
            tree.set_style(el_49, "font-size", "13px");
            tree.set_style(el_49, "font-weight", "500");
            tree.set_style(el_49, "color", "#a1a1aa");
            tree.set_style(el_49, "background-color", "#18181b");
            tree.set_style(el_49, "padding", "8");
            tree.set_style(el_49, "padding-left", "16");
            tree.set_style(el_49, "padding-right", "16");
            tree.set_style(el_49, "border-radius", "20");
            tree.set_style(el_49, "width", "hug");
            tree.set_style(el_49, "height", "hug");
            // on:click -> cat_home (cb_idx=8)
            tree.add_event(el_49, "click", 8);
            if let Some(el) = tree.get_mut(el_49) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_49) { el.text = Some("Home Goods".into()); }
            let el_50 = tree.create("div");
            tree.append_child(el_45, el_50);
            honeycomb::canvas_app::register_pill("Sports".as_ptr(), 6, el_50);
            tree.set_style(el_50, "font-size", "13px");
            tree.set_style(el_50, "font-weight", "500");
            tree.set_style(el_50, "color", "#a1a1aa");
            tree.set_style(el_50, "background-color", "#18181b");
            tree.set_style(el_50, "padding", "8");
            tree.set_style(el_50, "padding-left", "16");
            tree.set_style(el_50, "padding-right", "16");
            tree.set_style(el_50, "border-radius", "20");
            tree.set_style(el_50, "width", "hug");
            tree.set_style(el_50, "height", "hug");
            // on:click -> cat_sports (cb_idx=9)
            tree.add_event(el_50, "click", 9);
            if let Some(el) = tree.get_mut(el_50) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_50) { el.text = Some("Sports".into()); }
            let el_51 = tree.create("div");
            tree.append_child(el_45, el_51);
            honeycomb::canvas_app::register_pill("Books".as_ptr(), 5, el_51);
            tree.set_style(el_51, "font-size", "13px");
            tree.set_style(el_51, "font-weight", "500");
            tree.set_style(el_51, "color", "#a1a1aa");
            tree.set_style(el_51, "background-color", "#18181b");
            tree.set_style(el_51, "padding", "8");
            tree.set_style(el_51, "padding-left", "16");
            tree.set_style(el_51, "padding-right", "16");
            tree.set_style(el_51, "border-radius", "20");
            tree.set_style(el_51, "width", "hug");
            tree.set_style(el_51, "height", "hug");
            // on:click -> cat_books (cb_idx=10)
            tree.add_event(el_51, "click", 10);
            if let Some(el) = tree.get_mut(el_51) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_51) { el.text = Some("Books".into()); }
            let el_52 = tree.create("div");
            tree.append_child(el_44, el_52);
            tree.set_style(el_52, "width", "fill");
            tree.set_style(el_52, "height", "hug");
            let el_53 = tree.create("div");
            tree.append_child(el_44, el_53);
            tree.set_style(el_53, "direction", "horizontal");
            tree.set_style(el_53, "gap", "6");
            tree.set_style(el_53, "height", "hug");
            tree.set_style(el_53, "width", "hug");
            tree.set_style(el_53, "align", "center");
            let el_54 = tree.create("div");
            tree.append_child(el_53, el_54);
            tree.set_style(el_54, "font-size", "12px");
            tree.set_style(el_54, "color", "#52525b");
            tree.set_style(el_54, "width", "hug");
            tree.set_style(el_54, "height", "hug");
            if let Some(el) = tree.get_mut(el_54) { el.text = Some("Sort:".into()); }
            let el_55 = tree.create("div");
            tree.append_child(el_53, el_55);
            tree.set_style(el_55, "font-size", "12px");
            tree.set_style(el_55, "font-weight", "500");
            tree.set_style(el_55, "color", "#a1a1aa");
            tree.set_style(el_55, "background-color", "#18181b");
            tree.set_style(el_55, "padding", "6");
            tree.set_style(el_55, "padding-left", "12");
            tree.set_style(el_55, "padding-right", "12");
            tree.set_style(el_55, "border-radius", "6");
            tree.set_style(el_55, "width", "hug");
            tree.set_style(el_55, "height", "hug");
            // on:click -> sort_price_asc (cb_idx=11)
            tree.add_event(el_55, "click", 11);
            if let Some(el) = tree.get_mut(el_55) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_55) { el.text = Some("Price ↑".into()); }
            let el_56 = tree.create("div");
            tree.append_child(el_53, el_56);
            tree.set_style(el_56, "font-size", "12px");
            tree.set_style(el_56, "font-weight", "500");
            tree.set_style(el_56, "color", "#a1a1aa");
            tree.set_style(el_56, "background-color", "#18181b");
            tree.set_style(el_56, "padding", "6");
            tree.set_style(el_56, "padding-left", "12");
            tree.set_style(el_56, "padding-right", "12");
            tree.set_style(el_56, "border-radius", "6");
            tree.set_style(el_56, "width", "hug");
            tree.set_style(el_56, "height", "hug");
            // on:click -> sort_price_desc (cb_idx=12)
            tree.add_event(el_56, "click", 12);
            if let Some(el) = tree.get_mut(el_56) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_56) { el.text = Some("Price ↓".into()); }
            let el_57 = tree.create("div");
            tree.append_child(el_53, el_57);
            tree.set_style(el_57, "font-size", "12px");
            tree.set_style(el_57, "font-weight", "500");
            tree.set_style(el_57, "color", "#a1a1aa");
            tree.set_style(el_57, "background-color", "#18181b");
            tree.set_style(el_57, "padding", "6");
            tree.set_style(el_57, "padding-left", "12");
            tree.set_style(el_57, "padding-right", "12");
            tree.set_style(el_57, "border-radius", "6");
            tree.set_style(el_57, "width", "hug");
            tree.set_style(el_57, "height", "hug");
            // on:click -> sort_name (cb_idx=13)
            tree.add_event(el_57, "click", 13);
            if let Some(el) = tree.get_mut(el_57) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_57) { el.text = Some("Name A→Z".into()); }
            let el_58 = tree.create("div");
            tree.append_child(el_13, el_58);
            tree.set_style(el_58, "direction", "horizontal");
            tree.set_style(el_58, "wrap", "true");
            tree.set_style(el_58, "gap", "20");
            tree.set_style(el_58, "height", "hug");
            tree.set_style(el_58, "width", "fill");
            // Prototypes: styles parsed once, cloned 10K times (zero string parsing in loop)
            let _proto_0 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "direction", "vertical");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "280px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "background-color", "#18181b");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "border-radius", "12");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "border-color", "#27272a");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "border-width", "1");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "gap", "0");
                _p
            };
            let _proto_1 = {
                let mut _p = honeycomb::element::Element::new("img");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "280px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "190px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "border-radius", "12");
                _p
            };
            let _proto_2 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "direction", "vertical");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "padding", "14");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "gap", "5");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "fill");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_3 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-size", "15px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-weight", "600");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "color", "#fafafa");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "hug");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_4 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-size", "12px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "color", "#71717a");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "hug");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_5 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-size", "12px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "color", "#f59e0b");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "hug");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_6 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "direction", "horizontal");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "gap", "8");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "align", "center");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "fill");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_7 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-size", "18px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-weight", "700");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "color", "#fafafa");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "hug");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_8 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "fill");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_9 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-size", "10px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-weight", "600");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "color", "#10b981");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "background-color", "#052e16");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "padding", "2");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "padding-left", "6");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "padding-right", "6");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "border-radius", "4");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "hug");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "height", "hug");
                _p
            };
            let _proto_10 = {
                let mut _p = honeycomb::element::Element::new("div");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-size", "13px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "font-weight", "600");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "color", "#000");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "background-color", "#ffa11e");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "padding", "12");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "border-radius", "8");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "min-height", "44px");
                honeycomb::element::ElementTree::apply_style_to_element(&mut _p, "width", "fill");
                _p
            };
            tree.reserve(products.len() * 8);
            for product in products.iter() {
                let el_59 = tree.create_from_prototype(&_proto_0);
                tree.append_child(el_58, el_59);
                let el_60 = tree.create_from_prototype(&_proto_1);
                tree.append_child(el_59, el_60);
                tree.set_attribute(el_60, "src", &product.image_url);
                let el_61 = tree.create_from_prototype(&_proto_2);
                tree.append_child(el_59, el_61);
                let el_62 = tree.create_from_prototype(&_proto_3);
                tree.append_child(el_61, el_62);
                if let Some(el) = tree.get_mut(el_62) { el.text_borrowed = Some(product.name); }
                let el_63 = tree.create_from_prototype(&_proto_4);
                tree.append_child(el_61, el_63);
                if let Some(el) = tree.get_mut(el_63) { el.text_borrowed = Some(product.category); }
                let el_64 = tree.create_from_prototype(&_proto_5);
                tree.append_child(el_61, el_64);
                if let Some(el) = tree.get_mut(el_64) { el.text = Some("★★★★☆".into()); }
                let el_65 = tree.create_from_prototype(&_proto_6);
                tree.append_child(el_61, el_65);
                let el_66 = tree.create_from_prototype(&_proto_7);
                tree.append_child(el_65, el_66);
                if let Some(el) = tree.get_mut(el_66) { el.text = Some(format!("${}.{:02}", (product.price_cents / 100), (product.price_cents - ((product.price_cents / 100) * 100))).to_string()); }
                let el_67 = tree.create_from_prototype(&_proto_8);
                tree.append_child(el_65, el_67);
                let el_68 = tree.create_from_prototype(&_proto_9);
                tree.append_child(el_65, el_68);
                if let Some(el) = tree.get_mut(el_68) { el.text_borrowed = Some(product.stock_status); }
                let el_69 = tree.create_from_prototype(&_proto_10);
                tree.append_child(el_61, el_69);
                // on:click -> add_to_cart (cb_idx=1)
                tree.add_event(el_69, "click", 1);
                if let Some(el) = tree.get_mut(el_69) { el.visual.cursor = 1; el.focusable = true; }
                if let Some(el) = tree.get_mut(el_69) { el.text = Some("Add to Cart".into()); }
                // Auto-detected filter pattern: register card for O(n) filtering
                if let Some(&card_id) = tree.get(el_58).and_then(|e| e.children.last()) {
                    tree.set_attribute(card_id, "category", &product.category);
                    honeycomb::canvas_app::register_filter_card(card_id, product.category.as_ptr(), product.category.len() as u32);
                }
            }
            let el_70 = tree.create("div");
            tree.append_child(el_13, el_70);
            tree.set_style(el_70, "direction", "horizontal");
            tree.set_style(el_70, "gap", "8");
            tree.set_style(el_70, "width", "fill");
            tree.set_style(el_70, "height", "hug");
            tree.set_style(el_70, "padding-top", "24");
            tree.set_style(el_70, "align", "center");
            tree.set_style(el_70, "justify", "center");
            let el_71 = tree.create("div");
            tree.append_child(el_70, el_71);
            tree.set_style(el_71, "font-size", "11px");
            tree.set_style(el_71, "color", "#52525b");
            tree.set_style(el_71, "width", "hug");
            tree.set_style(el_71, "height", "hug");
            if let Some(el) = tree.get_mut(el_71) { el.text = Some(".nectar → Rust → WASM · Zero JavaScript · Rendered on Canvas".into()); }
            // Conditional block: cart_open == "1" — elements always created, visibility toggled
            let el_72 = tree.create("div");
            tree.append_child(el_12, el_72);
            honeycomb::canvas_app::register_conditional("cart_open", "1", el_72);
            if cart_open != 1 {
                tree.get_mut(el_72).map(|e| e.style.display_none = true);
            }
            tree.set_style(el_72, "direction", "vertical");
            tree.set_style(el_72, "width", "fill");
            tree.set_style(el_72, "height", "fill");
            tree.set_style(el_72, "background-color", "rgba(0,0,0,0.6)");
            tree.set_style(el_72, "padding", "0");
            tree.set_style(el_72, "padding-right", "32");
            tree.set_style(el_72, "padding-top", "16");
            tree.set_style(el_72, "gap", "0");
            tree.set_style(el_72, "align", "end");
            tree.set_style(el_72, "z-index", "10");
            let el_73 = tree.create("div");
            tree.append_child(el_72, el_73);
            tree.set_style(el_73, "direction", "vertical");
            tree.set_style(el_73, "width", "380px");
            tree.set_style(el_73, "height", "hug");
            tree.set_style(el_73, "background-color", "#18181b");
            tree.set_style(el_73, "border-color", "#27272a");
            tree.set_style(el_73, "border-width", "1");
            tree.set_style(el_73, "border-radius", "12");
            tree.set_style(el_73, "padding", "24");
            tree.set_style(el_73, "gap", "16");
            tree.set_style(el_73, "align", "start");
            let el_74 = tree.create("div");
            tree.append_child(el_73, el_74);
            tree.set_style(el_74, "direction", "horizontal");
            tree.set_style(el_74, "width", "fill");
            tree.set_style(el_74, "height", "hug");
            tree.set_style(el_74, "align", "center");
            let el_75 = tree.create("div");
            tree.append_child(el_74, el_75);
            tree.set_style(el_75, "font-size", "20px");
            tree.set_style(el_75, "font-weight", "700");
            tree.set_style(el_75, "color", "#fafafa");
            tree.set_style(el_75, "width", "fill");
            tree.set_style(el_75, "height", "hug");
            if let Some(el) = tree.get_mut(el_75) { el.text = Some("Your Cart".into()); }
            let el_76 = tree.create("div");
            tree.append_child(el_74, el_76);
            tree.set_style(el_76, "font-size", "14px");
            tree.set_style(el_76, "font-weight", "500");
            tree.set_style(el_76, "color", "#a1a1aa");
            tree.set_style(el_76, "background-color", "#27272a");
            tree.set_style(el_76, "padding", "8");
            tree.set_style(el_76, "padding-left", "14");
            tree.set_style(el_76, "padding-right", "14");
            tree.set_style(el_76, "border-radius", "6");
            tree.set_style(el_76, "width", "hug");
            tree.set_style(el_76, "height", "hug");
            // on:click -> close_cart (cb_idx=3)
            tree.add_event(el_76, "click", 3);
            if let Some(el) = tree.get_mut(el_76) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_76) { el.text = Some("Close".into()); }
            let el_77 = tree.create("div");
            tree.append_child(el_73, el_77);
            tree.set_style(el_77, "width", "fill");
            tree.set_style(el_77, "height", "1px");
            tree.set_style(el_77, "background-color", "#27272a");
            let el_78 = tree.create("div");
            tree.append_child(el_73, el_78);
            tree.set_style(el_78, "direction", "vertical");
            tree.set_style(el_78, "width", "fill");
            tree.set_style(el_78, "height", "hug");
            tree.set_style(el_78, "gap", "12");
            tree.set_style(el_78, "padding-top", "4");
            let el_79 = tree.create("div");
            tree.append_child(el_78, el_79);
            tree.set_style(el_79, "direction", "horizontal");
            tree.set_style(el_79, "width", "fill");
            tree.set_style(el_79, "height", "hug");
            tree.set_style(el_79, "align", "center");
            let el_80 = tree.create("div");
            tree.append_child(el_79, el_80);
            tree.set_style(el_80, "font-size", "14px");
            tree.set_style(el_80, "color", "#a1a1aa");
            tree.set_style(el_80, "width", "fill");
            tree.set_style(el_80, "height", "hug");
            if let Some(el) = tree.get_mut(el_80) { el.text = Some("Items in cart".into()); }
            let el_81 = tree.create("div");
            tree.append_child(el_79, el_81);
            tree.set_style(el_81, "font-size", "18px");
            tree.set_style(el_81, "font-weight", "700");
            tree.set_style(el_81, "color", "#fafafa");
            tree.set_style(el_81, "width", "hug");
            tree.set_style(el_81, "height", "hug");
            if let Some(el) = tree.get_mut(el_81) { el.text = Some(format!("{}", cart_count).to_string()); }
            honeycomb::canvas_app::register_metric_text("cart_count".as_ptr(), 10, el_81);
            honeycomb::canvas_app::register_text_binding(el_81, "cart_count".as_ptr(), 10, "{}".as_ptr(), 2);
            let el_82 = tree.create("div");
            tree.append_child(el_73, el_82);
            tree.set_style(el_82, "width", "fill");
            tree.set_style(el_82, "height", "1px");
            tree.set_style(el_82, "background-color", "#27272a");
            let el_83 = tree.create("div");
            tree.append_child(el_73, el_83);
            tree.set_style(el_83, "direction", "vertical");
            tree.set_style(el_83, "width", "fill");
            tree.set_style(el_83, "height", "hug");
            tree.set_style(el_83, "gap", "10");
            let el_84 = tree.create("div");
            tree.append_child(el_83, el_84);
            tree.set_style(el_84, "font-size", "14px");
            tree.set_style(el_84, "font-weight", "600");
            tree.set_style(el_84, "color", "#000");
            tree.set_style(el_84, "background-color", "#ffa11e");
            tree.set_style(el_84, "padding", "14");
            tree.set_style(el_84, "border-radius", "8");
            tree.set_style(el_84, "min-height", "44px");
            tree.set_style(el_84, "width", "fill");
            tree.set_style(el_84, "align", "center");
            tree.set_style(el_84, "justify", "center");
            // on:click -> checkout (cb_idx=4)
            tree.add_event(el_84, "click", 4);
            if let Some(el) = tree.get_mut(el_84) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_84) { el.text = Some("Checkout".into()); }
            let el_85 = tree.create("div");
            tree.append_child(el_83, el_85);
            tree.set_style(el_85, "font-size", "14px");
            tree.set_style(el_85, "font-weight", "500");
            tree.set_style(el_85, "color", "#a1a1aa");
            tree.set_style(el_85, "background-color", "#27272a");
            tree.set_style(el_85, "padding", "14");
            tree.set_style(el_85, "border-radius", "8");
            tree.set_style(el_85, "min-height", "44px");
            tree.set_style(el_85, "width", "fill");
            tree.set_style(el_85, "align", "center");
            tree.set_style(el_85, "justify", "center");
            // on:click -> close_cart (cb_idx=3)
            tree.add_event(el_85, "click", 3);
            if let Some(el) = tree.get_mut(el_85) { el.visual.cursor = 1; el.focusable = true; }
            if let Some(el) = tree.get_mut(el_85) { el.text = Some("Continue Shopping".into()); }
        });
    });
}

fn ecommercepanel_init_data() {
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.status = format!("Fetching 10,000 products from API...");
    });
}

fn ecommercepanel_on_data_loaded() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.product_count = state.products.len() as i32;
        state.status = format!("{} products fetched from database", state.product_count);
    });
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().heap_ms = honeycomb::canvas_app::get_heap_ms());
    // Re-render after state change
    let _t_rebuild = perf_now();
    // Clear stale registrations before tree rebuild
    honeycomb::canvas_app::clear_registrations();
    with_tree(|tree| {
        let root = tree.root_id();
        if let Some(el) = tree.get_mut(root) { el.children.clear(); }
    });
    ecommercepanel_mount();
    let _t_mounted = perf_now();
    render();
    let _t_laid = perf_now();
    {
        let msg = format!("REBUILD mount={:.2}ms layout={:.2}ms", _t_mounted - _t_rebuild, _t_laid - _t_mounted);
        unsafe { console_log(msg.as_ptr(), msg.len() as u32); }
    }
    let _total = to_ms_string(unsafe { INIT_START }, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().total_ms = _total.clone());
    update_metric_text("total_ms", &_total);
    let _pc = ECOMMERCEPANEL_STATE.with(|s| format!("{}", s.borrow().product_count));
    update_metric_text("product_count", &_pc);
}

fn ecommercepanel_add_to_cart() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.cart_count = (state.cart_count + 1);
    });
    // Simple state update — targeted text binding updates (no tree rebuild)
    { let _val = ECOMMERCEPANEL_STATE.with(|s| format!("{}", s.borrow().cart_count)); honeycomb::canvas_app::update_text_bindings("cart_count", &_val); }
    honeycomb::canvas_app::mark_gpu_dirty();
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_toggle_cart() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.cart_open = (1 - state.cart_open);
    });
    // Reactive conditional toggle — O(1) visibility, no tree rebuild
    { let _val = ECOMMERCEPANEL_STATE.with(|s| format!("{}", s.borrow().cart_open)); honeycomb::canvas_app::toggle_conditional("cart_open", &_val); }
    honeycomb::canvas_app::relayout_conditional("cart_open");
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_close_cart() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.cart_open = 0;
    });
    // Reactive conditional toggle — O(1) visibility, no tree rebuild
    { let _val = ECOMMERCEPANEL_STATE.with(|s| format!("{}", s.borrow().cart_open)); honeycomb::canvas_app::toggle_conditional("cart_open", &_val); }
    honeycomb::canvas_app::relayout_conditional("cart_open");
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_checkout() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.cart_count = 0;
        state.cart_open = 0;
    });
    // Reactive conditional toggle — O(1) visibility, no tree rebuild
    { let _val = ECOMMERCEPANEL_STATE.with(|s| format!("{}", s.borrow().cart_open)); honeycomb::canvas_app::toggle_conditional("cart_open", &_val); }
    { let _val = ECOMMERCEPANEL_STATE.with(|s| format!("{}", s.borrow().cart_count)); honeycomb::canvas_app::update_text_bindings("cart_count", &_val); }
    honeycomb::canvas_app::relayout_conditional("cart_open");
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_cat_all() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.active_cat = "All".to_string();
    });
    // O(n) filter: auto-detected from template {if} pattern
    let _fv = ECOMMERCEPANEL_STATE.with(|s| s.borrow().active_cat.clone());
    honeycomb::canvas_app::apply_filter(&_fv);
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_cat_electronics() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.active_cat = "Electronics".to_string();
    });
    // O(n) filter: auto-detected from template {if} pattern
    let _fv = ECOMMERCEPANEL_STATE.with(|s| s.borrow().active_cat.clone());
    honeycomb::canvas_app::apply_filter(&_fv);
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_cat_clothing() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.active_cat = "Clothing".to_string();
    });
    // O(n) filter: auto-detected from template {if} pattern
    let _fv = ECOMMERCEPANEL_STATE.with(|s| s.borrow().active_cat.clone());
    honeycomb::canvas_app::apply_filter(&_fv);
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_cat_home() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.active_cat = "Home Goods".to_string();
    });
    // O(n) filter: auto-detected from template {if} pattern
    let _fv = ECOMMERCEPANEL_STATE.with(|s| s.borrow().active_cat.clone());
    honeycomb::canvas_app::apply_filter(&_fv);
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_cat_sports() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.active_cat = "Sports".to_string();
    });
    // O(n) filter: auto-detected from template {if} pattern
    let _fv = ECOMMERCEPANEL_STATE.with(|s| s.borrow().active_cat.clone());
    honeycomb::canvas_app::apply_filter(&_fv);
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_cat_books() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.active_cat = "Books".to_string();
    });
    // O(n) filter: auto-detected from template {if} pattern
    let _fv = ECOMMERCEPANEL_STATE.with(|s| s.borrow().active_cat.clone());
    honeycomb::canvas_app::apply_filter(&_fv);
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_sort_price_asc() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.sort_mode = "Price ↑".to_string();
        { let _k: Vec<i32> = state.products.iter().map(|p| p.price_cents as i32).collect(); honeycomb::canvas_app::apply_sort_by_i32(&_k, true); };
    });
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_sort_price_desc() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.sort_mode = "Price ↓".to_string();
        { let _k: Vec<i32> = state.products.iter().map(|p| p.price_cents as i32).collect(); honeycomb::canvas_app::apply_sort_by_i32(&_k, false); };
    });
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

fn ecommercepanel_sort_name() {
    let _op_t0 = perf_now();
    ECOMMERCEPANEL_STATE.with(|s| {
        let mut state = s.borrow_mut();
        state.sort_mode = "Name A→Z".to_string();
        { let mut _idx: Vec<u32> = (0..state.products.len() as u32).collect(); _idx.sort_by_cached_key(|&i| state.products[i as usize].name.clone()); honeycomb::canvas_app::apply_sort_by_indices(&_idx); };
    });
    let _op_elapsed = to_ms_string(_op_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().last_op_ms = _op_elapsed.clone());
    update_metric_text("last_op_ms", &_op_elapsed);
}

// ── Render: layout only (painting done by Honeycomb's app_render) ──

fn render() {
    honeycomb::wasm_api::TREE.with(|t| {
        let mut tree = t.borrow_mut();
        let mut measurer = EstimateMeasurer;
        let vw = unsafe { canvas_get_width() };
        let vh = unsafe { canvas_get_height() };
        layout::compute(&mut tree, vw, 999999.0, &mut measurer);
    });
}

#[no_mangle]
pub extern "C" fn nectar_init(_vw: f32, _vh: f32) {
    let _init_t0 = perf_now();
    unsafe { INIT_START = _init_t0; }
    ecommercepanel_init_data();
    ecommercepanel_mount();
    let _init_elapsed = to_ms_string(_init_t0, perf_now());
    ECOMMERCEPANEL_STATE.with(|s| s.borrow_mut().total_ms = _init_elapsed.clone());
    update_metric_text("total_ms", &_init_elapsed);
    let _heap = ECOMMERCEPANEL_STATE.with(|s| s.borrow().heap_ms.clone());
    update_metric_text("heap_ms", &_heap);
    // Auto-fetch: init_data detected, firing fetch with callback
    fetch_get("/api/products?per_page=10000", 0);
}

#[no_mangle]
pub extern "C" fn __callback(idx: u32) {
    if idx == 0 {
        // Zero-copy JSON parse: leak response buffer so Product borrows &'static str
        let _t_copy = perf_now();
        let (_status, body) = read_response();
        let body: &'static [u8] = Box::leak(body.into_boxed_slice());
        let _t_copied = perf_now();
        ECOMMERCEPANEL_STATE.with(|s| {
            let mut state = s.borrow_mut();
            if let Ok(parsed) = serde_json::from_slice::<Vec<Product>>(&body) {
                state.products = parsed;
            }
        });
        let _t_parsed = perf_now();
        {
            let msg = format!("FETCH BREAKDOWN: copy={:.2}ms serde_parse={:.2}ms body={}bytes", _t_copied - _t_copy, _t_parsed - _t_copied, body.len());
            unsafe { console_log(msg.as_ptr(), msg.len() as u32); }
        }
    }
    match idx {
        0 => ecommercepanel_on_data_loaded(),
        1 => ecommercepanel_add_to_cart(),
        2 => ecommercepanel_toggle_cart(),
        3 => ecommercepanel_close_cart(),
        4 => ecommercepanel_checkout(),
        5 => ecommercepanel_cat_all(),
        6 => ecommercepanel_cat_electronics(),
        7 => ecommercepanel_cat_clothing(),
        8 => ecommercepanel_cat_home(),
        9 => ecommercepanel_cat_sports(),
        10 => ecommercepanel_cat_books(),
        11 => ecommercepanel_sort_price_asc(),
        12 => ecommercepanel_sort_price_desc(),
        13 => ecommercepanel_sort_name(),
        _ => {}
    }
}
